3b1b/manim

.gitignore
README.md
constants.py
requirements.txt

I came across your youtube videos and wanted to figure out how to use this software because its awesome!
I added a `requirements.txt` file with the dependencies that I could find (with notes about `aggdraw` in the readme) and switched the output dir to something within the folder. And added some basic setup notes in the readme.
However I'm still getting the following error while trying to run `python extract_scene.py generate_logo.py`
```
File "extract_scene.py", line 205, in main
handle_scene(SceneClass(**scene_kwargs), **config)
File "/Users/scott/scratch/manim/scene/scene.py", line 32, in __init__
self.construct(*self.construct_args)
File "/Users/scott/scratch/manim/./generate_logo.py", line 50, in construct
self.interpolation_factor
TypeError: …
```

How to use

---

helpers.py

Changing background color by adding config to a scene is not possible. it is overridden by the config defined in constants (LOW_QUALITY_CAMERA_CONFIG), even when the constant does not define the color. This happens because the "camera_config" is nested, so its content is never compared.
With this change nested configuration is merged instead of overridden. The change is tested on several scenes from hanoi.py, and does not break any of the tested scenes.

Merge nested configs instead of overriding

---

extract_scene.py

Modified sound when done if there is a runtime error (in case of quitting if -p is present)

Modified a little thing

---

helpers.py

An explanation of why I changed this can be found here:
[https://codepen.io/anthonynorthrup314/full/qVLWJY/](https://codepen.io/anthonynorthrup314/full/qVLWJY/)

Corrected partial_bezier_points

---

extract_scene.py
scene/scene.py

While writing to a movie file, if you specify -f it will export a png
sequence in a folder with the same name like the scene. The ability to
export transparent PNG sequences adds the ability to change the
background afterwards.

Ability to export PNG sequence

---

topics/number_line.py

double drawing of elongated ticks fixed

---

active_projects/basel.py
topics/geometry.py

An Arc's center was incorrectly calculated. The method only worked if the center was in the origin.

Corrected get_arc_center()

---

active_projects/WindingNumber.py
animation/simple_animations.py
helpers.py

Having made fixes to the implementation of Succession animations, these fixes should be pulled into master.

Winding number

---

active_projects/fourier.py
mobject/mobject.py
mobject/vectorized_mobject.py
stage_scenes.py
topics/characters.py
topics/geometry.py
topics/number_line.py

Finished first Fourier project

Fourier work

---

active_projects/WindingNumber.py
animation/simple_animations.py
camera/camera.py
container/__init__.py
container/container.py
helpers.py
mobject/mobject.py
scene/scene.py

MObject and Scene are now derived from Container. Succession and AnimationGroup have had various bugs fixed. (Also, incremental progress on WindingNumber, unimportant to others, is bundled into this.)

MObject and Scene are now derived from Container

---

topics/three_dimensions.py

Take into account the camera distance in `get_view_transformation_matrix()`.

[3D CAMERA] BUGFIX: Zoom

---

helpers.py

Tiny addon. All is in the title.

[HELPER] Add a color helper function

---

example_scenes.py
topics/three_dimensions.py

New feature: give the possibility to change the center of rotation.

[3D CAMERA] Center of rotation

---

topics/three_dimensions.py

While this isn't perfect, it is a way to graph a 3D surface using square approximations. (Also apparently some linting got in, which I can change if necessary.)

Add 3D graphing via square approximation.

---

topics/three_dimensions.py

Revert "Add 3D graphing via square approximation."

---

primes.py

Updated imports in primes.py (you missed it in a previous commit)

Updated imports

---

README.md

README.md: Ensure that Python 3 is used

---

README.md

#313 has prepared this repo for free, automated flake8 testing on each pull request but it must be enabled by @3b1b logging into https://travis-ci.com/profile via GitHub id and flipping the repository switch on.

Capitalization and test to see if Travis CI is turned on

---

README.md

Added line linking to guide to help new users edit their own Dockerfile, but without the link part...

Fixed link for Dockerfile consultation.

---

README.md

Todd Zimmerman put together a newer tutorial for manim, that works on python 3.7. I thought that putting this on the README might be useful for those who want to get started, since it was the first thing I read about manim.

Adding a newer tutorial by Todd Zimmerman

---

Dockerfile

The final image size should be much smaller. You can squish it down a bit more but the difference in size isn't that big.

updated the docker file to use fewer layers.

---

manimlib/scene/scene.py
manimlib/utils/output_directory_getters.py

Issue: https://github.com/3b1b/manim/issues/401
I use windows platform and when testing the example, ffmpeg cannot find 0.mp4 and the partial_movie_file_list.txt. Moreover, the partial files and directory are not deleted when finished.
Testing:
Before:
Command: python -m manim example_scenes.py SquareToCircle
After: 
Same Command

The file problem on Windows

---

manimlib/mobject/coordinate_systems.py
manimlib/scene/scene_file_writer.py
manimlib/scene/three_d_scene.py

A few bug fixes, in light of [this issue](https://github.com/3b1b/manim/issues/428).

Checkpoints

---

manimlib/mobject/types/vectorized_mobject.py

When I tried to write some Chinese words I found the "not defined" error, and I fix it.

Import the function "rotate_vector"

---

example_scenes.py
manimlib/animation/composition.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/mobject.py

Added a few mobject methods, like set_x, get_x, match_x, (likewise for y, z).

Align to changes

---

active_projects/aliquot.py
manimlib/mobject/geometry.py
manimlib/mobject/mobject_update_utils.py
manimlib/mobject/three_dimensions.py
manimlib/mobject/types/vectorized_mobject.py

- Added general get_arc_length to VMobject
- Improved Polygon.round_corners
- Added f_always

Small VMobject changers

---

manimlib/mobject/svg/svg_mobject.py

Currently the SVG parsing code found in svg_mobject.py does not include a few edge-cases from [W3 SVG 2.0](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands). The current condition of the code would not allow users to follow the repo recommended SVG tutorial by   [TalkingPhysics](https://talkingphysics.wordpress.com/2019/01/08/getting-started-animating-with-manim-and-python-3-7/).
In particular, edge cases outlined in the description for "moveto" and "cubic Bezier curve" commands.
* "M" or "m" keywords can contain consecutive relative line-to coordinates after the initial moveto coordinates.
* "C" or "c" keywords can contain consecutive control points for polybezier.
The case with "C" keywords had a corresponding snippet of code attempting to address this issue, however, a bug …

Fixed SVG parsing error with consecutive C or M coordinates.

---

.travis.yml

Output: https://travis-ci.org/3b1b/manim/builds/522690304#L252

Use ==/!= to compare str, bytes, and int literals

---

README.md

People discovering this engine on GitHub might not have context on it, or know what it looks like. Linking to YouTube allows people to see examples of the engine in action.

Link to 3Blue1Brown channel in the README intro.

---

manimlib/mobject/functions.py

I wanted to draw a parameterized curve whose 't' goes from -1 to plus infinity
yep

smarter parameterized curve

---

README.md
environment.yml

Added an `environment.yml` file to create a conda environment. 
Updated README instructions for creating the conda environment and running manim. 
The conda environment was created. Its functioning was tested by running the `example_scenes.py`.  
Closes #519

Added anaconda environment and windows instructions

---

.travis.yml
manimlib/for_3b1b_videos/common_scenes.py
manimlib/once_useful_constructs/fractals.py
manimlib/scene/vector_space_scene.py

Hopefully this will get the travis build working properly.

tweak travis configuration

---

README.md

Improved the wording and presentation of the "Using manim" section in the README file.

Improved the "Using manim" section in the README

---

docs/about.rst

Fixed typo in the docs about page

---

docs/source/conf.py

A small change, mostly to see under what conditions travis doesn't start a new build.

add master_doc to conf.py

---

docs/source/index.rst

Adding information to the docs, again to test when Travis starts a build.

add information to docs

---

README.md

Beginning of lines 6 and 7 are the same, but Subreddit and Discord is not the same.

Correction of a bad alt description

---

.gitignore
manimlib/mobject/geometry.py

Add an overview of TipableVMobject's functionality and a few comments, as well as grouping some methods by functionality (roughly).
---------------------------------------------
Just a bit of documentation :) I'm trying to go through manim's source code and see how it all fits together.
As you'd expect, given that I'd only added a few multi-line comments and grouped a few methods together, the scenes in example_scenes.py rendered correctly w/o any dramas.

Documentation for TipableVMobject

---

docs/source/getting_started/making_a_scene.rst

I filled in the making_a_scene file for the documentation. No changes were made to manimlib, so it should still be just as functional as it was.

Filled out making_a_scene in the docs

---

docs/source/installation/linux.rst

Arch Linux installation guild

---

docs/source/installation/mac.rst

MiKTeX hasn't been working correctly on macOS, but MacTeX works.

Updated macOS installation

---

manimlib/extract_scene.py

It is basically the same as the previous version when ALL_SCENE_CLASSES was used.

Fix the list of scenes.py

---

manimlib/extract_scene.py

Add a feature

---

README.md

fixed manim

---

active_projects/hyperdarts.py
active_projects/spirals.py
manimlib/animation/composition.py
manimlib/animation/creation.py
manimlib/for_3b1b_videos/common_scenes.py
manimlib/mobject/geometry.py
manimlib/mobject/types/point_cloud_mobject.py
manimlib/scene/scene.py
old_projects/name_animation.py
stage_scenes.py

Animations from the video on Prime spirals, conflated with a few on the hyperdarts video.

Hyperdarts

---

manimlib/scene/scene_file_writer.py

Change way to remove sound_file_path

Solve issue add sound in Windows 10

---

docs/source/installation/windows.rst

docs typo mistake mentioned in #803

#803 docs typo mistake

---

docs/source/installation/windows.rst

Fix simple typo: installtion -> installation

---

docs/source/constants.rst

Documentation typo in constants.rst

---

manimlib/animation/transform.py

I know this is trivial, but I had to fix it.

Fix "itslef" to "itself"

---

example_scenes.py

docs typo mistake mentioned in #806

#806 typo in WriteStuff

---

manimlib/mobject/mobject.py

Small typo in mobject.py

---

README.md

Update readme to reflect #571

---

manimlib/imports.py

I have fixed a very simple typo and would like to commit it.

Fixed typo in comment imports.py

---

manimlib/scene/scene.py

Fix typo in scene.py

---

example_scenes.py

Fixed a typo in exapmle_scenes.py

---

example_scenes.py
manimlib/imports.py
manimlib/mobject/interactive.py
manimlib/mobject/mobject.py
manimlib/scene/scene.py
manimlib/utils/space_ops.py

Having sliders, textbox, checkbox, etc will speed up the development process of videos and it can also help in some videos that include explanations of how things change when some parameters are tweaked.
( Source code of the above interactive is added in **example_scenes.py** )
* It can be used during development purposes for tweaking parameters and seeing the changes live.
* It can also be used for explanation videos that consist of tweaking parameters.
* For videos, instead of mouse and keyboard, you can change Interactive Mobject Values using the **set_value** method.
* Like ValueTracker, you can add updaters to other mobjects which changes mobject state using interactive mobjects **get_value** method.
1. manimlib/mobject/mobject.py
> Added event handlers methods and "listen_to_events" …

Interactive Mobjects in Manim

---

README.md

updated installation of manim on macOS

---

manimlib/mobject/value_tracker.py

"Note meant to be displayed" -> "Not meant to be displayed". Just a small typo fix!

Fix typo in value_tracker.py

---

manimlib/extract_scene.py

mulziple -> multiple, line 35.
just a simple grammar correction that I noticed while using manim.

Grammar correction

---

.github/workflows/publish.yml
README.md
manimlib/config.py
manimlib/defaults.yml
manimlib/window.py
setup.cfg

I added the code to package manimlib and publish it on pypi using GitHub Action. Also fixed some bugs that made manimlib unable to be used normally after packaging.
- The first commit https://github.com/3b1b/manim/commit/9916f56fb10b8600856b37e1bb84b57f5cc63ad2: The package will not include `manim.py`, so the "manim" module will not be found. So I changed to get the manimlib directory, and returned to the previous level to get the original "manim_dir".
- The second commit https://github.com/3b1b/manim/commit/e4df135bbea9f6c8e57ef597e796bccd03b4fe58: Updated the version and document address in `setup.cfg`.
- The third commit https://github.com/3b1b/manim/commit/7a6a8556b87c3f7b307127dea100b8892dab0eba: The package will also not include `custom_default.yml`, so I created the same …

Package manimlib and automatically publish to pypi

---

manimlib/scene/scene.py
requirements.txt

rebased #1161
> - removed unused `progressbar` dependency
> - correct `ascii` fallback auto-detection, related https://github.com/tqdm/tqdm/issues/454

progress fixes

---

manimlib/animation/creation.py
manimlib/animation/indication.py
manimlib/animation/transform_matching_parts.py
manimlib/camera/camera.py
manimlib/config.py
manimlib/constants.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/frame.py
manimlib/mobject/matrix.py
manimlib/mobject/mobject.py
manimlib/mobject/number_line.py
manimlib/mobject/numbers.py
manimlib/mobject/shape_matchers.py
manimlib/mobject/svg/brace.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/tex_mobject.py
manimlib/mobject/svg/text_mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/mobject/vector_field.py
manimlib/once_useful_constructs/light.py
manimlib/utils/directories.py
manimlib/utils/images.py
manimlib/window.py

Various bug fixes and changes made during the project on matrix exponents.  Notable changes include:
- Allow variable stroke width
- Add FlashAround and FlashUnder animations
- By default, keep mobjects from shrinking to size 0 by using min_scale_factor in Mobject.scale
- Add CameraFrame.reorient method

Matrix exp development

---

README.md
docs/source/getting_started/installation.rst

See 
https://github.com/3b1b/manim/issues/1387
https://github.com/3b1b/manim/issues/1391
ManimPango should be installed from the source for Linux users.
Also, see https://github.com/ManimCommunity/ManimPango/issues/27
update docs

update docs for linux installation

---

requirements.txt

manimpango v0.3.0 should work as there are no breaking changes for the API used here
I should bring in MarkupText here...

requirements.txt: manimpango v0.3.0

---

manimlib/mobject/svg/text_mobject.py
manimlib/utils/space_ops.py

The function `earclip_triangulation` works incorrectly with polygons with many holes. It is mentioned in #1331, but not fixed completely. The function goes wrong mainly for two reasons:
- Simply choose the closest pair of points may fail with characters that contain a ◫-like structure in it. In the following picture, the two blue edges will be added first, and the dot (outside the large square) will connect with either of the small squares (inside the large square). This happens with 疆 in the SimHei font.
- Because the first and the last point of a ring is the same, the connected ring might be self-crossed at this point (as the following gif shows). It's usually caused by a 田-like structure. This happens with 画 in the SimHei font.
The red squares are two rings passed to the function (and …

Temporary hack for showing text correctly

---

README.md

In the Manim discord, we often see people confused about the different versions of Manim, using the community instructions to install manimgl or vice versa. Adding this clarification should help lessen the confusion and potentially save hours for many people.

Add clarification on versions

---

manimlib/mobject/mobject.py

Add another rotation to make it work.
Here are some tests.
https://user-images.githubusercontent.com/86904416/128203385-0116e14e-4827-41dc-9ef4-a6732c3a115d.mp4
https://user-images.githubusercontent.com/86904416/128203399-f1f60d5a-ac32-4581-99d8-a80055666696.mp4

fix put_start_and_end_on

---

docs/source/getting_started/configuration.rst
docs/source/getting_started/example_scenes.rst
example_scenes.py
manimlib/animation/transform.py
manimlib/mobject/mobject.py
manimlib/mobject/mobject_update_utils.py
manimlib/mobject/shape_matchers.py
manimlib/once_useful_constructs/graph_theory.py
manimlib/once_useful_constructs/region.py
manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py
manimlib/utils/bezier.py
manimlib/utils/iterables.py
manimlib/window.py

fixing typo grammar for more readable
- fix typo grammar and replace to correct words with reference from [merriam webster](https://www.merriam-webster.com/)
not include test because just replace typo grammar with correct words

fix: fix typo spelling grammar

---

manimlib/mobject/mobject.py
manimlib/mobject/numbers.py

Alternate fix with the side effects of https://github.com/3b1b/manim/pull/1591

Revert scale changes

---

docs/example.py

Fix the import statement
- 
- 
- 
**Code**:
**Result**:

Fix the import

---

manimlib/animation/transform_matching_parts.py
manimlib/config.py
manimlib/extract_scene.py
manimlib/mobject/geometry.py
manimlib/mobject/three_dimensions.py
manimlib/mobject/types/dot_cloud.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py

Updates made to the core library made while animating the next 3b1b video. Includes a few new Mobjects, like Dodecahedron and GlowDot, along with miscellaneous bug fixes.

Video work

---

manimlib/mobject/svg/mtex_mobject.py

- M `manimlib/mobject/svg/mtex_mobject.py`

Add a staticmethod for tex rendering in MTex

---

manimlib/animation/creation.py
manimlib/animation/specialized.py
manimlib/mobject/matrix.py
manimlib/mobject/svg/svg_mobject.py
manimlib/once_useful_constructs/graph_theory.py
manimlib/scene/vector_space_scene.py

- Minor edits
- Remove unnecessary imports
- Remove duplicated keys
- Add `,` for symmetry's sake (unneeded because it's `join`ed anyway but still)
- Remove `time_per_edge`

Imports update, dict keys removal etc.

---

manimlib/scene/scene.py

See the first bug of https://github.com/3b1b/manim/issues/1741#L66

Presenter mode bug fix

---

manimlib/camera/camera.py
manimlib/mobject/three_dimensions.py
manimlib/mobject/types/vectorized_mobject.py

A few minor bug fixes and addition associated with camera and 3d mobjects.

Small camera/3d updates

---

manimlib/mobject/svg/labelled_string.py
manimlib/mobject/svg/text_mobject.py

- M `manimlib/mobject/svg/labelled_string.py`: remove unnecessary raise statement
- 
- 
**Code**:
**Result**:

Remove unnecessary raise statement

---

manimlib/mobject/number_line.py
manimlib/utils/bezier.py

Separate functionality of ordinary linear interpolation from that using np.outer on arrays

Interpolate fix

---

manimlib/animation/creation.py

Learning Python and Math and then found this awesome tool
Nothing but a deletion of a unused import, see image below
<kbd>
</kbd>
**Code**: Not applicable
**Result**: Not applicable

Remove unused import

---

manimlib/animation/transform.py

Fixes https://github.com/3b1b/manim/issues/1857

Fix Restore

---

manimlib/mobject/types/vectorized_mobject.py

Fix typo in vectorized_mobject.py

---

example_scenes.py
manimlib/animation/composition.py
manimlib/config.py
manimlib/extract_scene.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/geometry.py
manimlib/scene/scene.py

- Several bug fixes associated with https://github.com/3b1b/manim/pull/1932
- Refactor checkpoint_paste
- Change functionality of -e flag to rewrite file in place, rather than creating an alternate file

Small bug fixes and refactorings

---

manimlib/config.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/svg/mtex_mobject.py
manimlib/mobject/svg/string_mobject.py
manimlib/mobject/svg/text_mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py
manimlib/utils/color.py

- Better height, width, unit_size behavior for CoordinateSystems
- Go back to writing a new file for insert_embed, handling __file__ issue differently

Small bug fixes and refactors

---

example_scenes.py
manimlib/animation/transform_matching_parts.py
manimlib/camera/camera.py
manimlib/mobject/geometry.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/string_mobject.py
manimlib/mobject/types/dot_cloud.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py
manimlib/shader_wrapper.py
manimlib/shaders/inserts/camera_uniform_declarations.glsl
manimlib/shaders/inserts/get_unit_normal.glsl
manimlib/shaders/inserts/quadratic_bezier_geometry_functions.glsl
manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_fill/geom.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl
manimlib/shaders/quadratic_bezier_stroke/vert.glsl
manimlib/utils/family_ops.py
manimlib/utils/space_ops.py
manimlib/utils/tex.py
manimlib/window.py

- Simplify Scene.remove to not require a Mobject.get_ancestors call
- Various bug fixes for Tex
- Write an alternate TransformMatchingStrings / TransformMatchingTex
- No longer track unit normal in VMobject data
- Fix some antialiasing bugs for VMobject fill
- Some speed-ups associated with VMobject.get_shader_wrapper_list

Miscellaneous fixes and tweaks

---

example_scenes.py
manimlib/animation/composition.py
manimlib/camera/camera.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/tex_mobject.py
manimlib/scene/scene.py
manimlib/shader_wrapper.py
manimlib/utils/color.py
manimlib/utils/tex.py

- Add Tex.make_number_changable (see TexAndNumbersExample in example_scenes.py)
- Interpolate colors using square of rgbs
- Fix various little bugs
- Mobject.looks_identical failed for non-numpy array data attrs
- LaggedStartMap failed with FlashAround
- Camera.get_pixel_array returned upside-down image

More tweaks and fixes

---

example_scenes.py
manimlib/animation/fading.py
manimlib/animation/transform_matching_parts.py
manimlib/mobject/svg/string_mobject.py
manimlib/mobject/svg/tex_mobject.py

Together with a few small miscellaneous changes.

Refactor TransformMatchingStrings/TransformMatchingShapes

---

LICENSE.md

-  Changed the year in the Licence to current year

update the year

---

manimlib/camera/camera.py
manimlib/mobject/mobject.py
manimlib/mobject/numbers.py
manimlib/mobject/types/vectorized_mobject.py

Small fix from an oversight in https://github.com/3b1b/manim/pull/1959
(Along with some small tweaks)

Fix index buffer bug

---

manimlib/__init__.py
manimlib/animation/composition.py
manimlib/animation/creation.py
manimlib/animation/indication.py
manimlib/animation/transform_matching_parts.py
manimlib/camera/camera.py
manimlib/mobject/geometry.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_fill/geom.glsl
manimlib/shaders/quadratic_bezier_fill/vert.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl
manimlib/typing.py
manimlib/utils/iterables.py
manimlib/utils/shaders.py

- Edits to winding fill to ensure it works better with transparency and works regardless of orientation
- Fix issues with arrow and variable stroke width
- Various fixes based on recent changes to ShaderWrapper

Miscellaneous bug fixes

---

manimlib/mobject/types/vectorized_mobject.py

Possible fix for https://github.com/3b1b/manim/issues/1976

Possible fix for a type error

---

manimlib/mobject/types/vectorized_mobject.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_fill/geom.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl
manimlib/shaders/quadratic_bezier_stroke/vert.glsl

One theory for what's going on with https://github.com/3b1b/manim/issues/1975#issuecomment-1410906866 and https://github.com/3b1b/manim/issues/1405#issuecomment-1410741180 is that the usage of gl_VertexID was causing problems. This removes dependence on that.

Change VMobject rendering mode to TRIANGLES

---

manimlib/mobject/changing.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/geometry.py
manimlib/mobject/matrix.py
manimlib/mobject/mobject.py
manimlib/mobject/numbers.py
manimlib/mobject/shape_matchers.py
manimlib/mobject/three_dimensions.py
manimlib/mobject/types/dot_cloud.py
manimlib/mobject/types/point_cloud_mobject.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/mobject/value_tracker.py
manimlib/mobject/vector_field.py

Add [Self](https://peps.python.org/pep-0673/) as the return type for many Mobject methods

Add Self type

---

example_scenes.py
manimlib/animation/creation.py
manimlib/animation/transform.py
manimlib/animation/transform_matching_parts.py
manimlib/camera/camera.py
manimlib/camera/camera_frame.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/drawings.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_stroke/geom.glsl
manimlib/utils/dict_ops.py
manimlib/utils/shaders.py

- Fix shadow glitch in https://github.com/3b1b/manim/issues/1405
- Allow setting mult-color style with tuples
- Fix a glitch with how strokes looked during Write animation
- Fix Camera.blit
- Make fill border draw on top by default

Various bug fixes and tweaks

---

manimlib/mobject/mobject.py
manimlib/scene/interactive_scene.py
manimlib/window.py

- Change the behavior of clicking (it does not select mobjects by default)
- Allow for copying a command that will animate to the current frame position
- Better mobject copying during Scene embeds

Interactive scene update

---

example_scenes.py
manimlib/animation/composition.py
manimlib/animation/transform.py
manimlib/animation/transform_matching_parts.py
manimlib/camera/camera_frame.py
manimlib/config.py
manimlib/extract_scene.py
manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/mobject/vector_field.py
manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py
manimlib/shader_wrapper.py
manimlib/utils/shaders.py
manimlib/window.py

- FIx Mobject.replace_shader_code
- Make prerunning a scene (to count the total number of frames) optional, and default to false
- Add set_program_uniform function which only changes uniforms values if necessary
- Fix undo/redo/checkpoint paste in light of render groups
- Make Mobject.has_same_shape_as more lenient

A few more fixes and tweaks.

---

manimlib/mobject/types/vectorized_mobject.py

In response to https://github.com/3b1b/manim/issues/1991

Fix for index -3 error

---

manimlib/animation/transform.py
manimlib/config.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/mobject.py
manimlib/mobject/mobject_update_utils.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene_file_writer.py

- Add options for saturation on colors in exported videos
- Ensure joint_products are refreshed for _AnimationBuilder
- Fix transparent background videos

Several bug fixes

---

example_scenes.py

Removed old argument from example

---

manimlib/shaders/quadratic_bezier_stroke/geom.glsl

Clean up stroke geometry shader, and account for an edge case for non-flat stroke when the tangent lines up with camera view.

3d stroke bug fix

---

manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene_file_writer.py
manimlib/shaders/quadratic_bezier_stroke/frag.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl

See https://github.com/3b1b/manim/issues/2158

Fix low resolution thin stroke issue

---

manimlib/mobject/boolean_ops.py

https://github.com/3b1b/manim/issues/2174

Fix issue with Difference

---

setup.cfg

As per https://github.com/3b1b/manim/issues/2227#issuecomment-2432775443

Add mapbox-earcut dependency

---

manimlib/shader_wrapper.py
manimlib/shaders/textured_surface/frag.glsl
requirements.txt

- Add missing dependence.
- A fix for https://github.com/3b1b/manim/issues/2146.  It's not perfect, e.g. with partial opacity objects with paths of multiple orientations, but it should address most cases.

Misc. bug fixes

---

README.md

I saw that the Readme was a little (tiny) bit unreadable, so I took the liberty to update it a little : ]
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R18-R21): Added a warning callout to specify that the instructions are only for ManimGL and a note callout to highlight the correct package name for installation.
I did not run a test per say, but the Readme looks better now 
**Code**:
**Result**:

Update README.md for better readability

---

manimlib/scene/scene.py
manimlib/scene/scene_embed.py
setup.cfg

- Fixing `get_ipython` import in `scene.py` and `scene_embed.py` files.
- Adding the required packages in `setup.cfg` file.

Minor Import Bug Fixed + Adding Required Packages

---

manimlib/utils/tex_file_writing.py

To address https://github.com/3b1b/manim/issues/2293

Only use -no-pdf for xelatex rendering
