README.md

This fixes the issue I mentioned in #1 
I had to patch aggdraw because pillow 3.x broke compatibility with PIL as best I can tell.
They discuss the issue [here](https://github.com/python-pillow/Pillow/issues/63), and they seem to revert it, but it seems to be a fatal error in pillow 3.2.0 and this fixes it.
The usage and install directions should work now without any trouble!

updates instructions using my patched version of aggdraw for pillow 3.x

---

animation/transform.py

The apply method animation plays in reverse for nested VMobjects. See the following code as an example. The square should move from left to right, but actually moves from right to left:
```
o = NestedObject()
self.add(o)
self.dither()
self.play(ApplyMethod(o.update))
self.dither()
class NestedObject(VMobject):
def __init__(self, **kwargs):
VMobject.__init__(self, **kwargs)
self.square = Square();
self.square.move_to(LEFT_SIDE)
self.add(self.square)
def update(self):
self.square.move_to(RIGHT_SIDE,RIGHT_SIDE)
return self 
```
I believe this is caused by the ApplyMethod function creating only a shallow copy of the original object. So the method is applied to the original nested VMObject, instead of a copy.
I'm not totally confident about this …

Fixed ApplyMethod animation going in reverse for nested objects

---

mobject/tex_mobject.py

Whenever latex fails (for example due to a missing package) the code
continue and ends up failing due to a missing svg file.
Handle latex non 0 exit code.
Pass to latex -halt-on-error so it does not attempt to ask user for a
file, that is ignored in batch mode anyway.
Write the latex output to stderr and raise an exception to abort early.
Signed-off-by: Antoine Musso <hashar@free.fr>

Handle latex errors when converting to dvi

---

README.md
requirements.txt

pip is able to install a python module straight from a git repository
and supports pinning a specific commit.
Add scottopell/aggdraw-64bits to requirements.txt
Adjust README.md to drop the manual install step now covered by pip
install.
Test plan
I have created an empty virtual env on Debian GNU/Linux and ran the demo
command:
python extract_scene.py -p example_scenes.py SquareToCircle
Signed-off-by: Antoine Musso <hashar@free.fr>

Make pip to install aggdraw from github

---

mobject/mobject.py

All is in the title.
More precisely, an error showed up when trying to use a scene in `old_projects/triangle_of_power/triangle.py`, as the DrawInsideTriangle scene. (Works on Windows and Linux, fix due to @shahar603 in issue #30)

Deleted the cast error in class TOP

---

extract_scene.py

Implemented the solution I suggested in issue #28.
The changes I did were to split `get_module` to two functions: `get_module_windows` and `get_module_posix`.
So now `get_module` check the OS and directs to the appropriate function.
(I tested this only on Windows 10).

Added support for Windows (hopefully)

---

mobject/tex_mobject.py
scene/scene.py

1. Added `get_null` function in `mobject/tex_mobject.py` to obtain the correct "blackhole directory". Hopefully `tex_to_dvi` and `dvi_to_svg` functions will now work properly on multiple platforms including Windows.
2. Replaced `os.rename` with `shutil.move` to avoid [WindowsError 183].

Improved stability for Windows NT OS

---

template.tex
text_template.tex

Simple modifications to tex templates.
I tested all 6 available fonts in `ctex` package, and they work pretty fine with CJ characters in both `TextMobject` (plain text) and `TexMobject` (formula).
P.S.: I should've say "CJK characters", but for some reason, Korean characters aren't able to display normally on my computer, so I dropped them for now.

Added support for Chinese and Japanese characters

---

Dockerfile
README.md
requirements.txt

It seems that getting the dependencies installed just right for this project is quite tricky, so I decided to write a Dockerfile to eliminate/standardize that headache.
It ended up being fairly straightforward with the final usage going from:
`python extract_scenes.py example_scenes.py WarpSquare`
to
`docker run --rm -v "$PWD"/files:/app/files manim example_scenes.py WarpSquare`
which, while longer, doesn't add any more work for the user and could be hidden behind an alias or shell script if desired.
Any thoughts on if this is something you'd be interested in?
Also, I had to revert the requirements.txt changes to using my version of aggdraw and pillow, I couldn't get it to work using your versions.
How do you setup aggdraw and pillow? I can try to make it work with your versions.
Keep up …

Docker Support

---

constants.py

In the constant.py script, I propose to use `makedirs()` instead of `mkdir()`. This allow the recursive creation of directories.

[CONST] Fix directories creation

---

mobject/tex_mobject.py

1. Modified `highlight_by_tex_to_color_map()` so that it's able to accept a dictionary with both string and tuple as keys.
For example, the following color_map is now valid:
`{"x": BLUE, ("y", "z"): YELLOW}`
2. Also, the keyword argument `substring` should work properly in `highlight_by_tex_to_color_map()`.
3. Added some special characters in `modify_special_strings()`.

A few improvements on TexMobject

---

animation/simple_animations.py

Fixed bug where AnimationGroups did not propagate configs correctly under update_config (in particular, this was a problem when nested AnimationGroups were initializing).
Fixed bug where AnimationGroups did not filter out empty animations correctly from their initialization of self.sub_anims (as they digested their configurations before doing this filtering).

Winding number

---

scene/scene.py

Default behavior is now to include the render quality in the name of the directory where files are written, so that low quality tests don't necessarily clobber the existing HD versions.

Change redered filed directory names

---

extract_scene.py

If one is under Linux, use the command `xdg-open` to open the generated video.
This PR fixes the Issue #103.
It is also potentially relative to Issue #185.

[PREVIEW] Fix the preview under Linux

---

requirements.txt

All in the title.
If I don't install `opencv-python` under Ubuntu, I get the following error:
```
$ python extract_scene.py example_scenes.py SquareToCircle -pl
File "extract_scene.py", line 266, in <module>
main()
File "extract_scene.py", line 223, in main
module = get_module(config["file"])
File "extract_scene.py", line 219, in get_module
return get_module_posix(file_name)
File "extract_scene.py", line 213, in get_module_posix
last_module = imp.load_module(part, *load_args)
File "/home/frozar/wk/manim/./example_scenes.py", line 3, in <module>
from big_ol_pile_of_manim_imports import *
File "/home/frozar/wk/manim/big_ol_pile_of_manim_imports.py", line 66, in <module>
from scene.scene_from_video import *
File …
```

[CONFIG] Add opencv-python in requirements.

---

.gitignore
constants.py

This pull request adds an easy way to reconfigure the media directories:
- You can have the environment variable MEDIA_DIR set, in which case it will use this and remember it
- You can have already set once the MEDIA_DIR environment variable, in which case it will use the last set
- Otherwise, it will defaults to a default directory.
In all cases, it will remember the choice and write it in a file (which is used in case you don't have the MEDIA_DIR variable set).

Added a way to easily customize the media directory

---

extract_scene.py

In accordance with Issue #281, this is simply a way to make color changing easier, especially for specific scenes. That said, I'm not sure if @3b1b wants this feature or not, especially since this can already be edited in configs for specific scenes. Nevertheless, it provides a similar method as transparency.
This edits the camera config in the same way as the resolution argument or transparency flag. Inputs can either be strings, 3 digit hex strings, or 6 digit hex strings. In a Unix terminal the hex strings will have to be prepended with a '\'.

Added the option to change color in extract scene.

---

Dockerfile

The current Dockerfile was written for python 2, which is no longer supported. This updates it for python 3.

update Dockerfile for python 3

---

.travis.yml
README.md

Fixes #284
Another attempt at #99 
Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.
__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

Run free Travis CI and flake8 tests on all new code submissions

---

old_projects/nn/network.py

__get_norm()__ is called on lines 259 and 265 but it is never imported or defined.
[flake8](http://flake8.pycqa.org) testing of https://github.com/3b1b/manim on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./old_projects/bell.py:222:38: E999 SyntaxError: invalid syntax
for here, x in (here1, 0), (here2, 4)
^
./old_projects/borsuk.py:217:11: E999 SyntaxError: invalid syntax
y=lambda m: m1.get
^
./old_projects/eoc/chapter6.py:399:35: E999 SyntaxError: invalid syntax
for i, j in (1, 0), (0, 1)
^
./old_projects/nn/network.py:258:16: F821 undefined name 'get_norm'
norm = get_norm(gradient)
^
./old_projects/nn/network.py:264:15: F821 undefined name 'get_norm'
print(get_norm(old_pre_sig_guess - pre_sig_guess))
^
3     E999 SyntaxError: …
```

from utils.space_ops import get_norm

---

old_projects/bell.py
old_projects/eoc/chapter6.py

Fixes two of the problems below...
[flake8](http://flake8.pycqa.org) testing of https://github.com/3b1b/manim on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./old_projects/bell.py:222:38: E999 SyntaxError: invalid syntax
for here, x in (here1, 0), (here2, 4)
^
./old_projects/borsuk.py:217:11: E999 SyntaxError: invalid syntax
y=lambda m: m1.get
^
./old_projects/eoc/chapter6.py:399:35: E999 SyntaxError: invalid syntax
for i, j in (1, 0), (0, 1)
^
./old_projects/nn/network.py:258:16: F821 undefined name 'get_norm'
norm = get_norm(gradient)
^
./old_projects/nn/network.py:264:15: F821 undefined name 'get_norm'
print(get_norm(old_pre_sig_guess - pre_sig_guess))
^
3     E999 SyntaxError: invalid syntax
2     F821 undefined name 'get_norm' …
```

 Explicit tuple required in comprehension in Python 3 

---

README.md

Otherwise GitHub sets the wrong prefix which results in:
https://github.com/3b1b/manim/blob/master/manim.readthedocs.io

Prefix the link to the documentation with https:// .

---

constants.py
for_3b1b_videos/pi_creature.py
mobject/svg/svg_mobject.py
old_projects/eola/chapter0.py
once_useful_constructs/__init__.py

Although [scenes involving pi creatures are intended to fall back to the plain one](https://github.com/3b1b/manim/issues/18#issuecomment-299902614), the configuration for `PiCreature` mobjects actually prevents it from working.
This pr achieves three things:
1. Fix the logic preventing `PiCreatures` from falling back correctly
2. Make some of the latex in `/old_projects/eola/chapter0.py` more compliant (my latex compiler simply threw an error)
3. Make `/once_useful_constructs/__init__.py` into a package, so that scenes in `old_projects` can import it

Fix fallback to plain pi creature and make once_useful_constructs into a package

---

mobject/svg/svg_mobject.py

Some fonts (like mathpazo) produce svg files which use single scale-factor transform (like `transform=scale(1.3)`). Previously the behavior of this code was to throw an unpacking exception in the try block, which resulted in the font glyphs misrendering. 
I would think that the `about_point` should be `ORIGIN` for the [scale_x, scale_y, 1] block as well, but I only put that change in the `elif` clause so that the proposed change would be non-breaking.

SVG single-factor scaling

---

mobject/svg/svg_mobject.py

I don't think this is nearly as bad a problem as I thought it was in #360. It seems that scaling only affects the appearance of the SVGMobject, but not its position.

Scale SVGMobject about origin

---

constants.py

A solution for #356. I verified this works by running `python extract_scene.py example_scenes.py SquareToCircle -pl` when `media/` did not exist, and verifying that it did and was written to afterward. This also occurs when a nonexistent directory is specified.

Automatically create MEDIA_DIR

---

README.md
config.py
constants.py
extract_scene.py
manim.py
scene/scene.py
stream_starter.py

This pull request handles a few housekeeping changes:
1. Makes manim into a module, so it can be added to `PYTHONPATH` and run from anywhere with `python -m manim`
2. Separates configuration, rendering, and constants into their own modules
3. Adds the `--livestream` flag, which runs manim in streaming mode
4. Replaces the `IS_LIVE_STREAMING`, `IS_STREAMING_TO_TWITCH`, and `TWITCH_STREAM_KEY` constants with flags

Config refactor

---

manimlib/extract_scene.py

Write to stderr and return 2 (problem encountered) when a scene isn't found

print to stderr for scene not found

---

.gitignore
manimlib/extract_scene.py

Previously, `manim` would fail when trying to open the finished video on Windows:
```
Writing to media\videos\..\example_scenes\480p15\SquareToCircleTemp.mp4
Animation 0: ShowCreationSquare: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 87.73it/s]
Animation 1: TransformSquareToCircle: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 155.48it/s]
Animation 2: FadeOutSquareToSquare: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 149.59it/s]
Played a total of 3 animations
File "D:\git\manim\manimlib\extract_scene.py", line …
```

Use os.openfile() on Windows and gitignore media folder

---

manimlib/config.py
manimlib/extract_scene.py

The success/failure sound isn't necessary when using manim as part of a larger application, so add an option to suppress it if desired.

Add option to suppress success/failure sound

---

manimlib/config.py
manimlib/utils/output_directory_getters.py

As was mentioned in #389, manim fails to render scenes that aren't contained in the root directory. This PR fixes that issue.
Testing:
```
(manim) > mkdir test
(manim) > cd test/
(manim) > python -m manim --no_sound ~/Public/manim/example_scenes.py SquareToCircle -l
Media will be stored in media/. You can change this behavior by writing a different directory to media_dir.txt.
Writing to media/videos/example_scenes/480p15/SquareToCircleTemp.mp4
Animation 0: ShowCreationSquare: 100%|██████████████| 15/15 [00:00<00:00, 164.53it/s]
Animation 1: TransformSquareToCircle: 100%|█████████| 15/15 [00:00<00:00, 292.01it/s]
Animation 2: FadeOutSquareToSquare: 100%|███████████| 15/15 [00:00<00:00, 279.36it/s]
Played a total of 3 animations
(manim) > python -m manim --no_sound …
```

allow rendering scenes from any directory

---

manimlib/camera/camera.py

The latest version of manim was giving a `NameError` in camera.py
```
Traceback (most recent call last):                                                                       
File "/home/azazel/Documents/fossee/manim/manimlib/extract_scene.py", line 138, in main                
handle_scene(SceneClass(**scene_kwargs), **config)                                                   
File "/home/azazel/Documents/fossee/manim/manimlib/scene/scene.py", line 78, in __init__               
self.construct(*self.construct_args)                                                                 
File "/home/azazel/Documents/fossee/manim/holomorphic.py", line 33, in construct                       
self.zoom_in_to_one_plus_half_i()                                                                    
File …
```

added import copy to camera.py

---

manimlib/mobject/coordinate_systems.py

Test case:
```python
#!/usr/bin/env python
from big_ol_pile_of_manim_imports import *
class TestScene(Scene):
axes = Axes()
self.play(ShowCreation(axes))
```

Fixed a ZeroDivisionError when instantiating Axes

---

active_projects/clacks/name_bump.py
manimlib/camera/camera.py
manimlib/config.py
manimlib/constants.py
manimlib/extract_scene.py
manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py
manimlib/scene/scene_from_video.py
manimlib/scene/three_d_scene.py
manimlib/stream_starter.py
old_projects/bell.py
stage_scenes.py

- Use frame_rate, instead of frame_duration, and make that part of the camera rather than the scene
- Allow scene extraction from a special file which contains an ALL_SCENE_CLASSES list and an OUTPUT_DIRECTORY. This is part of a move to make the output file organization independent from the source code organization

Scene file writer refactor

---

manimlib/utils/tex_file_writing.py

I have faced issues where German "umlauts" (such as `ä`, `ö` or `ü`) would not be encoded correctly, since the standard encoding on Windows is `Windows 1252` rather than `UTF-8`.
This PR changes the TeX file encoding to be explicitly `UTF-8`.

Made sure to always encode written TeX files as UTF-8

---

manimlib/constants.py

Unprivileged users are typically granted read-only access to library code for security reasons. Manim currently prevents this protection by writing to its own directory whenever a Scene generates latex. This change allows a user to specify a `files` directory through an environment variable.
Note that this, along with the option to specify `MEDIA_DIR` through an environment variable are only a temporary fix. The default behavior should be to write all files to a reasonable location that the user can access.

Optionally specify files directory with FILE_DIR environment variable

---

manimlib/mobject/geometry.py

Constructing an ellipse before gave the error "name 'width' is not defined"
I got this error when running the tutorial at https://github.com/zimmermant/manim_tutorial/blob/master/manim_tutorial_P37.py.
python3 -m manim manim_tutorial_P37.py MoreShapes -pl
File "/Users/jeanwhitmore/Code/python3/manim/manimlib/extract_scene.py", line 153, in main
scene = SceneClass(**scene_kwargs)
File "/Users/jeanwhitmore/Code/python3/manim/manimlib/scene/scene.py", line 52, in __init__
self.construct()
File "manim_tutorial_P37.py", line 33, in construct
ellipse=Ellipse(width=3, height=1, color=RED)
File "/Users/jeanwhitmore/Code/python3/manim/manimlib/mobject/geometry.py", line 319, in __init__
self.set_width(width, stretch=True)
NameError: name 'width' is not defined …

Fix Ellipse constructor: 'width' is not defined

---

manimlib/scene/scene_file_writer.py

I kept getting an error:
`/Users/rodrigo_temp.castellon/Desktop/misc/pi-day/manim/media/videos/example_scenes/480p15/partial_movie_files/SquareToCircle/00000_temp.mp4: No such file or directory`
Notice how this path doesn't actually exist since `rodrigo_temp.castellon` is not a valid directory, it used to be `rodrigo.castellon`.
So, the code used to produce the temp file path didn't take into account the possibility of paths including periods in other places other than right before the file extension.
the goal is to show us how you know the pull request works as …

Fixed `temp_file_path` to be more specific in adding the "_temp." string to file name

---

manimlib/constants.py

Currently, manim will always write `media_dir.txt` to the directory where it runs, even if the user sets the `FILE_DIR` and `MEDIA_DIR` environment variables. This is more of a security inconvenience than a security problem, but it's still rather impolite for manim to modify part of the filesystem without allowing the user to specify a different location.
Besides, this write isn't needed. If the media directory is read from `media_dir.txt`, then the file is already there. And if it is read from an environment variable, it can be passed via environment variable again.

Don't write media_dir

---

manimlib/mobject/geometry.py

This reverts the commit "Cleaned Up Arrow Implementation (d489b5df5c77...), which introduced a bug in the CurvedArrow constructor (https://github.com/3b1b/manim/issues/446).  I had to fix one conflict in the imports, making sure to import both libraries rather than only one.
Done with
git merge upstream/master
https://github.com/3b1b/manim/issues/446
Since I did not see an obvious fix and no one had addressed the bug in several days, I created a rollback now rather than risk more conflicts as other commits are made on top of the bug.
screenshots, gifs, …

Move get_length() into TipableVMobject

---

manimlib/scene/graph_scene.py

When I run manim, the position of several things is slightly off.  This fixes the position of the y-axis label.  I am running Python 3.7.0
This following is a before shot.
The following is an after shot:

Fix the position of the y-axis label

---

manimlib/mobject/geometry.py

The reason for this change is to fix a bug in `Ellipse` initialization. Currently it uses `self.width` for both `width and `height`, which creates a circle by  mistake.
The following code demonstrates this:
```
#!/usr/bin/env python
from big_ol_pile_of_manim_imports import *
class DrawEllipse(Scene):
ellipse = Ellipse()
self.play(ShowCreation(ellipse))
```
When run with the current code you get a circle, as shown in the first attachment:
When run with the change you get a proper ellipse:

Fix height setting in Ellipse initialization

---

manimlib/mobject/numbers.py
manimlib/scene/graph_scene.py

This fixes the alignment of the minus sign to negative numbers.
The `align_to` method was being called with an optional argument `alignment_vec` that did not do anything.
This is a before shot:
This is an after shot:

Fix alignment of minus sign to numbers

---

manimlib/mobject/types/vectorized_mobject.py

Fixes `VectorizedPoint.get_anchors()`, which previously returned an empty array when called on a `VectorizedPoint` (https://github.com/3b1b/manim/issues/455).
I tested by running the code found in that issue and verifying that the rectangles were placed properly.

fix get_anchors for VectorizedPoints

---

manimlib/extract_scene.py

This is all that's needed to allow manim to be used on [cygwin](https://cygwin.com/) (beyond the normal installation of dependencies including building ffmpeg within cygwin, of course).
`startswith` is needed because the value depends on the windows version &mdash; for me, it's `CYGWIN_NT-10.0` (this happens with the actual `uname` command; it's not a python thing).  [Relevant code](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/uname.cc;h=306cdee4a32faff42c5d34d3293325511e8ca77a;hb=HEAD#l95).  `os.startfile` does not exist when using cygwin (same as actual linux).
[Man page for `cygstart`](http://www.polarhome.com/service/man/?qf=cygstart&tf=2&of=Cygwin&sf=1).

Fix --preview on cygwin

---

README.md
manimlib/mobject/svg/tex_mobject.py

Using python3.x,  and there is a problem creating Matrix(). 
Error:
`TypeError: descriptor 'strip' requires a 'str' object but received a 'numpy.int64'`
And it can be solved by modify manimlib/mobject/svg/tex_mobject.py.
I've tested it, and it seems that it works for now.
Besides, just ignore the other four Commits...

Fix bug for creating Matrix

---

README.md

Adds a section under "Installation" that details all the steps necessary to getting manim to run on Windows. Tested on several Windows 10 machines with unvarying success.
Many users have found it difficult to get manim working properly on Windows machines (see #483, #444, #369, #359, #353, and countless closed issues). I may write a much more detailed blog post for using manim on Windows in the future.

Update README for Windows installation

---

README.md

Typo fix: remove redundant "the" in README

---

README.md
manimlib/constants.py
setup.py

I want to package manim for my distribution and made changes here so that it's easier for me and others to package it.
Now the project supports the standard Python packaging method of setuptools and we can install it using just `python3 -m pip install .` (even without a distribution packaging it). After installing we can use it in any directory - not just the source repository.
I'm still wondering which are the files that people are supposed to run.
`manim.py` is obviously the main one but does it allow access to all the functionality?
`stage_scenes.py` looks like it does something useful, but I can't figure out exactly what. See: #515 
`manimlib/extract_scene.py` has an `if __name__ == "__main__"` but that's broken because it doesn't call `main()` with all its parameters.
If you like the …

Make manim installable using setuptools (setup.py)

---

manimlib/config.py
manimlib/scene/scene_file_writer.py

The previous implementation of `get_default_output_directory()` used the relative path to the target module to create the output directory. This means that when the target module resides in a "sibling" directory (e.g. `../sibling_dir/scenes.py`), `get_default_output_directory()` would return an absolute path (`///sibling_dir/scenes`) and manim would attempt to write video there. This is not only unexpected but potentially dangerous, since files can be accidentally overwritten.
With this change, the default behavior is to save video in a directory under `VIDEO_DIR` named after the target module.

fix mishandled relative paths

---

example_scenes.py

It is a good option to mention because the current default for a high quality 60fps video is 2560x1440.
So, if someone wants a 1920x1080 video, they should pass -r 1080.

Mentioned -r argument in example_scenes comment

---

example_scenes.py

Changed `UdatersExample` to `UpdatersExample`.

Fixed typo in class name in example_scenes.py

---

requirements.txt

Many issues, such as #535, stem from the odd installation procedure of cairo and pycairo on Windows. By changing the pycairo requirement in requirements.txt, pip will no longer attempt to uninstall the working version. This should have no effect on the functionality of manim, though new installations are likely to default to pycairo 1.18.0 now.

Update pycairo requirement

---

docs/source/installation/linux.rst

The conf.py is broken when eulertour merged his doc fork to master. To test the doc add ``master_doc = "index"`` to conf.py  
I have not test this on a fresh system, the installation process is inferred from my bash history.

Add installation documentation for ubuntu

---

docs/source/installation/windows.rst

The installation is done with a Windows8 machine,
further testing are needed for windows10.
for example ``python`` will launch just fine, while doing so would result in a command not found in cmd.exe
Also I omitted the pypi installtion, for some reasons the pycairo whl install will be removed and force a recompile which #555 is supposed to fix? or just that pypi hasn't get updated yet ?
Installing collected packages: pycairo, manimlib
Found existing installation: pycairo 1.18.0
Uninstalling pycairo-1.18.0:
Successfully uninstalled pycairo-1.18.0
Running setup.py install for pycairo ... error
ERROR: Complete output from command 'c:\users\k\appdata\local\programs\python\python37-32\python.exe' -u -c 'import
setuptools, tokenize;__file__='"'"'C:\\Users\\K\\AppData\\Local\\Temp\\pip-install-30 …

Add Windows installation documentation

---

manimlib/ctex_template.tex

The textcomp package was imported twice in the ctex template.
See issue #552

Remove duplicate usepackage

---

requirements.txt

Choose pycairo version based on platform
#569 and #555 indicate that linux and windows require different versions of pycairo, so install the one needed by the platform.

Conditional requirements

---

manimlib/config.py
manimlib/scene/scene_file_writer.py

I added the option to save as gif, however the mp4 or mov file still needs to be saved as well. I'll be trying to find a workaround, but despite that it works. When using the -i option a .gif file will be saved to the output directory

add option -i to save as gif

---

docs/source/getting_started/index.rst
docs/source/index.rst
docs/source/installation/index.rst

While reading the documentation, I noticed some headings ending with a colon, namely "Contents:" and some without any punctuation at the end.
The latter is the typographical rule, so I thought we should follow it consistently.

Remove typographically incorrect punctuation from documentation headings

---

Dockerfile
docker-compose.yml
manimlib/config.py
manimlib/constants.py

The dockerfile now installs manim directly into the container, so there is no need to bind mount the library when running it. That said, you will still have to bind mount the places to read the source and write the video.
1080p rendering is now possible by passing the `--high_quality` flag, and I changed the 1080p frame rate from 30fps to 60fps.

update dockerfile, add flag for high quality rendering

---

docs/source/getting_started/index.rst

This pull request intends to update the docs. The link to Todd Zimmerman's tutorial is broken, this PR fixes that broken link.
Note that this PR is likely not ready to merge. Reading the updated tutorial it seems to have comprehensive changes, but I can't find the previous tutorial so I can't say what changed and I don't know what's up to date and what's become outdated since the January 2019 publication. I'm not confident the text describing this tutorial is still accurate, but I'm not sure how to correctly change that description.
>Todd Zimmerman put together [a very nice tutorial](https://talkingphysics.wordpress.com/2018/06/11/learning-how-to-animate-videos-using-%60%60manim%60%60-series-a-journey/) on getting started with `manim`, but is unfortunately outdated. It’s still useful for …

Update link to Todd Zimmerman tutorial

---

.travis.yml

__sudo: required__ no longer is...  [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo:__ in your __.travis.yml__, we recommend removing that configuration_"

Travis CI: The sudo tag is now deprecated

---

manimlib/config.py
manimlib/constants.py
manimlib/scene/scene_file_writer.py

Video is currently written to a directory named after the input module, which can lead to collisions if modules with the same name are used in a single project. This option allows specifying a video directory manually rather than using the default.

Add --video_output_dir flag

---

README.md

I think the documentation link  in the readme is outdated.

DOC: update documentation link in readme

---

manimlib/scene/scene.py

This is a compromise solution because this problem is caused by windows its own.
You can see this problem in [here](https://github.com/tqdm/tqdm/issues/454).
The problem picture:

Fix tqdm display problem in windows

---

requirements.txt

This solves #444
I never tested this pull request, but I had this error after installing from pip and running the `manim` script:
`ModuleNotFoundError: No module named 'readline'`
I then ran:
`py -m pip install pyreadline`
And got this:
... `Successfully installed pyreadline-2.1`
And now `manim` prints the help message instead of the above error.

Update requirements.txt to include pyreadline

---

environment.yml

Simple fix for no longer available `pyreadline` package. Installed via `pip`.

conda environment bug fix with pyreadline package, closes #662

---

manimlib/constants.py
manimlib/imports.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/text_mobject.py

Because the `TextMobject` is the subclass of `TexMobject`,
so it requires some latex-style behaviours in order to add some changes.
(e.g. other languages, font, slant and weight)
So I create `Text` mobject but you can still use `TextMobject`.
`Text` is a subclass of `SVGMobject`.
It uses `cairo` to generate text svgs.
It has a better UTF-8 support, multi-line support, and various options. 
It doesn't support mathematical formula(latex), 
you can use `TextMobject` or `TexMobject`.
You can create a text in manim like:
```
from manimlib.imports import *
class Demo(Scene):
text = Text('Hello, world!')
self.play(Write(text))
```
Unlike `TextMobject`, `Text` only receive one `str`.
When there is only one line, the space(`' '`) in front or back will be ignored.
`'\t'` is not …

New Text Mobject

---

manimlib/mobject/svg/svg_mobject.py

Closes: #747
I've created a separate scene with SVG mobject and after the fix the pins are there.
I'm not sure whether there are scenes depending on the stroke lines to not be drawn.

Add default stroke width for the svg mobjects

---

manimlib/mobject/svg/svg_mobject.py

Fix to interpret subsequent points of absolute MoveTo (M) command as absolute LineTo (L).
For #720, tested with codes and svg files from #720 
For MoveTo and absolute LineTo issue, tested with SVGCircleAndSquare scene from https://github.com/zimmermant/manim_tutorial/blob/37efeb93db5a266d92f85ea1f72aec5ba66bb312/manim_tutorial_P37.py#L735

Closes: #720

---

manimlib/mobject/coordinate_systems.py

Hello, I believe there was a typo in commit 77acc99.
Changing this allows to run the following example from Todd Zimmerman's tutorial.
```python
class SimpleField(Scene):
CONFIG = {
"plane_kwargs" : {
"color" : RED
},
}
plane = NumberPlane(**self.plane_kwargs)
plane.add(plane.get_axis_labels())
self.add(plane)
points = [x*RIGHT+y*UP
for x in np.arange(-5,5,1)
for y in np.arange(-5,5,1)
]
vec_field = []
for point in points:
field = 0.5*RIGHT + 0.5*UP
result = Vector(field).shift(point)
vec_field.append(result)
draw_field = VGroup(*vec_field)
self.play(ShowCreation(draw_field))
```

Typo in super() 77acc99

---

manimlib/shaders/quadratic_bezier_fill_frag.glsl

Some GLSL compilers are more sensitive to types than others. With this fix, my Intel HD Graphics 5500 (Broadwell GT2) gives no error on this script anymore.

Changed -1 to -1.0 for broader GPU suppot.

---

manimlib/config.py

Since the livestream option is was removed, revise the config to require an input filename.

Display help if no input file is specified

---

manimlib/camera/camera.py
manimlib/mobject/types/vectorized_mobject.py
perf_scenes.py

tl;dr: this is a significant performance improvement for many scenes. 1.7x - 2.6x improvement in animation it/s.
This is a small change to some of the hotest paths in rendering objects. The biggest win comes from not using np.allclose() to check if two points are close enough. In general, NumPy is awesome at operating on large arrays, but overkill for very tiny questions like this. Created a small function to determine if two points are close using the same algorithm, and limited it to 2D points since that's all we need in set_cairo_context_path().
A couple of other minor tweaks to reduce or eliminate other uses of NumPy in this path.
In general, it is better to avoid wrapping lists in np.array when a real NumPy array isn't actually needed.
Added a new file for performance test scenes, …

Performance improvement for most scenes

---

manimlib/mobject/svg/text_mobject.py

There were three bugs in the Text Class, and I fixed them, please merge it if possible.
The Text Class won't work __in the 'shaders' branch__, and it throws errors as follows:
Then I fixed this bug by __removing the last "M" command in the svg path strings__ which cairo generated automatically. After doing that, it run perfectly in the 'shaders' branch.
When display Text's __stroke__, it won't work as expected. Because the svg paths cairo made are not closed.
If I display the index of the points on the svg paths, it just likes follow:
Then I fixed this bug by __making the svg paths closed manually__.
After doing that, the stroke of Text display as we expected:
This is not a bug, just make the Text's __default size__ the __same__ as TextMobject, so we can easily change TextMobject to Text …

Fix three bugs(shaders/stroke/size) of Text Class (text_mobject.py) 

---

manimlib/mobject/svg/text_mobject.py

Fixed Three bugs of Text Class.
This pull request is the same as #1030
Without this, Text Class wouldn't work in the 'shaders' branch.

Fix Text Class's bugs in shaders branch (the same as #1030)

---

manimlib/utils/tex_file_writing.py

Modify path as posix style before transport it to system command to fix issue #505 
I ran the example_scenes.py and pass all cases.

latex can't recognize path seperator \\ in windows

---

manimlib/mobject/svg/brace.py

Without `import copy` lines 128 to 131 will throw an error. I've tested this edit in my local version of the library and it fixes the bug.

Add missing import to brace.py

---

manimlib/ctex_template.tex

This may solve some xelatex errors, like #1055 #1027 etc.
If `\usepackage[UTF8]{ctex}` doesn’t be placed at the top of `ctex_template.tex`, it may cause xelatex error even TexLive or MiKTeX is installed correctly.

A solution to xelatex error converting to xdv

---

manimlib/scene/scene_file_writer.py

Fixed the following deprecation warning caused by numpy:
`/manim/manimlib/scene/scene_file_writer.py:336: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.`
Tested on: python 3.8.1 ; numpy 1.19.1

fixed deprecation warning: tostring -> tobytes

---

manimlib/mobject/coordinate_systems.py

Due to ```move_to``` method, ```NumberPlane``` only works fine when the numberplane is symmetric about its center, which makes it infeasible to generate asymmetric grid, for instance, the first quadrant.
The fix is simple: replacing ```move_to``` with ```shift```. Here's an example to test if it works.
```
class TestNumberplaneFix(Scene):
self.add(NumberPlane(x_min=0, y_min=0))
self.wait()
```

Small fix to NumberPlane construction

---

manimlib/mobject/mobject.py

The "stretch_to_fit_depth" function is calling "rescale_to_fit" with the wrong dimension. Just corrected that.

Corrected a bug in stretch_to_fit_depth function

---

manimlib/mobject/mobject.py

this looks like stray code
get_merged_array is computed recursively on line 701 and appended to the result
the value computed on line 704 is discarded

remove superfluous code

---

manimlib/mobject/number_line.py

A very simple fix for `mobject.number_line.get_number_line()`
Closes https://github.com/3b1b/manim/issues/997
> In `manimlib/mobject/number_line.py` the method `get_unit_size()` is defined thus
> 
> ```python
> def get_unit_size(self):
>     return (self.x_max - self.x_min) / self.get_length()
> ```
> 
> However, the dividend should be flipped with the divisor:
> 
> ```python
> def get_unit_size(self):
>     return self.get_length() / (self.x_max - self.x_min)
> ```

Correctly return get_unit_size

---

manimlib/mobject/coordinate_systems.py

Allow Axes to change the color of coordinate labels
__before__ , we can't change the color of the coordinates' color.
```python
CONFIG = {
"camera_config": {
"background_color": WHITE,
},
}
plane = NumberPlane(axis_config={"stroke_color": BLACK})
plane.add_coordinates()
self.add(plane)
```
```python
plane.add_coordinates(number_config={"color": BLACK})
```
__after__, allow to use `number_config` to change the color:
```python
CONFIG = {
"camera_config": {
"background_color": WHITE,
},
}
plane = NumberPlane(axis_config={"stroke_color": BLACK})
plane.add_coordinates(number_config={"color": BLACK})
self.add(plane)
```

Allow Axes to change the color of coordinate labels

---

manimlib/mobject/svg/tex_mobject.py

I felt like using only white in BulletedList wasn't visually appealing, so the ability to change the color of the bullet seemed useful.
```python
l = BulletedList("Item 1", "Item 2", "Item 3", dot_color=BLUE)
```
produces

Add dot_color to BulletedList

---

environment.yml

1. After installing manim with Anaconda using the environment.yml file and running any script including the example_scenes.py script, one receives an error of "no module pygments installed" (to that effect). This dependency is in the requirements.txt file but not in the environment.yml file, therefore I added it for easier environment installation and setup.

Pygments added to environment.yml

---

manimlib/for_3b1b_videos/common_scenes.py

I fix a small bug in the OpeningQuote scene. This scene has an attribute `highlighted_quote_terms` that is a dictionary. 
In method `get_quote`, it was iterating only through the dictionary keys.
1.In Python 3.x the way iterate through a dictionary has changed, hence it was incompatible with new Python versions.
2. I tested with my videos.

fix iteration through a dictionary

---

requirements.txt

pip will by default install the newest version of library. The newest pycairo(which manimlib needs) is now version [1.20.0](https://pypi.org/project/pycairo/#history) released on October 6th, 2020. But unfortunately pycairo 1.20.0 uses [PEP 517](https://www.python.org/dev/peps/pep-0517/) to build, which still has problems with virtualenv that travis-ci or other users rely on.
See the current travis-ci output [message](https://travis-ci.org/github/3b1b/manim/jobs/737736332#L377).
The second newest pycairo version on pip now is 1.19.1, and will not cause the ci to fail. In the future, new version of pycairo should always be tested to see if it's working, otherwise it's safer to specify a particular version of pycairo that works.

Specify pycairo version to 1.19.1

---

.travis.yml
requirements.txt

This is the second fix to pr #1264. 
The original travis-ci build environment is Ubuntu xenial, which is version 16.04 (see this information on travis-ci [document page](https://docs.travis-ci.com/user/reference/linux)), and the newest cairo version on it is 1.14, which caused problem with the newset pycairo 1.20.0. See the previous travis-ci [error message](https://travis-ci.org/github/3b1b/manim/jobs/737736332#L372).
Ubuntu bionic will not cause the problem, and redundant pycairo version can be removed.

Change Ubuntu version to bionic in .travis.yml

---

manimlib/scene/scene_file_writer.py

I accidentally found this "word", and I'm pretty sure there's no such word 'permananant'. I think @Aathish04 means the word 'permanent'.

fix typo docstring in scene_file_writer.py

---

custom_defaults.yml
environment.yml
example_scenes.py
manimlib/config.py
manimlib/constants.py
manimlib/mobject/svg/text_mobject.py
manimlib/scene/scene.py
requirements.txt

Continued https://github.com/3b1b/manim/pull/1315#issuecomment-761285165
Although `Text` can be colored properly in some cases, the position of non-display characters is not very good, and tabs are not processed. Because the #1035 of the master is not synchronized to the shaders. So I added them (https://github.com/3b1b/manim/commit/5f6b653803e3b138a2c9337c4a22dead375299c8) and made some changes (https://github.com/3b1b/manim/commit/3d118a5bb6d0dd55111dc8bc496db07d010f26d9) to fit the shaders branch.
And for this part (↓), if modify `SVGMobject` as in #1035, it may cause some problems for SVG, so I only modified the generated svg file in `Text` and deleted the empty path.
https://github.com/3b1b/manim/blob/5f6b653803e3b138a2c9337c4a22dead375299c8/manimlib/mobject/svg/text_mobject.py#L92-L9 …

Improve Text's handling of non-display characters in shaders and Add a feature

---

example_scenes.py
manimlib/mobject/interactive.py
manimlib/scene/scene.py

As mentioned in https://github.com/3b1b/manim/pull/1323#issuecomment-769350572, interactive mobjects were a bit laggy.
So, to improve interactively mobjects performance, the following changes are made.
1. Maintain a separate list of mobject listeners instead of filtering mobjects on every frame.
>   This significantly improved the performance on all events except the on_mouse_drag event. So to improve it the 2nd change was made.
2.  Changed the way drag events are handled.
> This improved the performance of on_mouse_drag event.
1. manimlib/scene/scene.py
> To store a separate list of mob_listners rather than checking it on every frame and changed the on_mouse_drag event handling. 
2. manimlib/mobject/interactive.py
> To adapt to the changes made in the way event handling works
3. …

Interactive Mobjects Performance Improvements

---

manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl

Similar to #950. On some machines, the return value of the function in GLSL is float, but returning 0 will cause an error. After changing it to 0.0, such an error will not occur.

Change 0 to 0.0 for broader GPU support

---

manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl

GLSL files viz; geom.glsl and frag.glsl has two functions angle_between_vectors and sdf. Their return type is float but returned 0(int) which caused glsl error in many gpus.
- Converted the 0 to 0.0 in return statement of angle_between_vectors and sdf

Converted 0 to 0.0 in sdf() and angle_between_vectors()

---

manimlib/utils/directories.py
manimlib/utils/file_ops.py

Just a minor fix!
I had configured default temporary location storage in custom_defaults.yml.
After running SurfaceExample from example_scenes.py, the earth textures were downloaded at the default system temp location rather than what was configured.
1. manimlib/utils/directories.py
> Added get_downloads_dir method
2. manimlib/utils/file_ops.py
> Changed downloads folder from tempfile.gettempdir() to get_downloads_dir
Now, the SurfaceExample Scene is downloading textures in the folder configured in custom_defaults.yml rather than system default temp dir.

Changed manim downloads location from default to custom_default config

---

manimlib/mobject/number_line.py

Currently the key `exclude_zero_from_default_numbers` of `NumberLine` is redundant since its value is not used anywhere else (including `coordinate_systems.py`) https://github.com/3b1b/manim/blob/fe85d4e02f6935c49fb0b88eebbd492dfff2d324/manimlib/mobject/number_line.py#L40 So, passing it as an argument to `NumberLine` won't produce the desired result. This PR removes the redundancy by replacing the key `exclude_zero_from_default_numbers` with `numbers_to_exclude` (defaults to `None`), which is passed as an argument to the method `add_numbers` at this line:
https://github.com/3b1b/manim/blob/fe85d4e02f6935c49fb0b88eebbd492dfff2d324/manimlib/mobject/number_line.py#L73 So `self.add_numbers()` becomes `self.add_numbers(excluding=self.numbers_to_exclude)`
1. Replace the redundant `CONFIG` key …

Replace redundant CONFIG key in NumberLine

---

manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py

this is a remake of https://github.com/3b1b/manim/pull/1204 on the current master
this way, decorated methods - typically Scene.play - have a decent docstring
so first-time users can use help()

handle_play_like_call decorator to use functools.wraps

---

manimlib/extract_scene.py

When prompted for Scene Selection,
1. The comma separator was not working.
2. Also, typing out the full scene is an error-prone tedious job. 
Since scene name (class name) can not be a numeric value, we could allow both options.
manimlib/extract_scene.py
> Changed prompt_user_for_choice method.
Comma-separated scene names or numbers are working properly.

Fixed prompt_user_for_choice and added number support

---

manimlib/mobject/number_line.py
manimlib/scene/graph_scene.py

Fixed #1354.
Temporarily fix the problem that occurs when `GraphScene` calls `NumberLine`. 
But I am not sure if it is necessary to continue to support `GraphScene`. If needed, then more adaptive changes should be made to `GraphScene`; if not, then it should be deleted.
- Change `self.tick_marks` to `self.ticks`
- Do not unpack when passing the value to `add_numbers()`
**Code**: The code in #1354 
```python
class Plot2yLabelNumbers(GraphScene):
CONFIG = {
"y_min": 0,
"y_max": 100,
"y_axis_config": {"tick_frequency": 10},
"y_labeled_nums": np.arange(0, 100, 10)
}
self.setup_axes()
dot = Dot().move_to(self.coords_to_point(PI / 2, 20))
func_graph = self.get_graph(lambda x: 20 * np.sin(x))
self.add(dot,func_graph)
```
**Result**:

Fix GraphScene and NumberLine

---

manimlib/mobject/number_line.py

Minor bugs concerning `unit_size` of `NumberLine`. 
1. The `get_unit_size` method 
https://github.com/3b1b/manim/blob/66817c4e2bc56f45f370498c2c93b033c1109951/manimlib/mobject/number_line.py#L125-L126 should return `self.get_length() / (self.x_max - self.x_min)`, not `(self.x_max - self.x_min) / self.get_length()`
2. If `width` is passed as an argument, the `unit_size` attribute (available via `CONFIG`) still remains 1 when it should be reset to appropriate value.
1. Fix the return value of `get_unit_size` method.
2. Reset the value of `unit_size` attribute if `width` is passed.

Fix NumberLine's unit_size

---

manimlib/mobject/geometry.py

Currently `Vector`s work only in 2d. If the `direction` passed for `Vector` extends into 3d, the resulting vector still lies on the XY plane (It's a vector in the direction given by `direction[:2]`, except for those along z-axis). Same is the case with `Arrow`s.  This happens because angle of the vector above the plane (90 - phi) is not considered currently. 
https://github.com/3b1b/manim/blob/66817c4e2bc56f45f370498c2c93b033c1109951/manimlib/mobject/geometry.py#L638 This accounts only for the angle of vector from x-axis (theta). Angle of the vector from z-axis(phi) is ignored.
- Rotate `Arrow`s (and thus, also `Vector`s) by an angle `90-phi` above the XY plane to place them correctly in 3d.
**Code**:
```py
class Vectors3DIssue(ThreeDScene):
frame = self.camera.frame …
```

Fix Vector orientation in 3d

---

manimlib/mobject/svg/text_mobject.py
requirements.txt

Pango is a lot better at Text Rendering rather than using a Toy API for Cairo. I had discussed this with @3b1b on [Discord.](https://discord.com/channels/581738731934056449/712140817200054294/808055730639863868). This will remove the dependency on pycairo.
It also provides another method to add a font file to Pango search path, whose family name can later be called. This method isn't available for macOS yet.
I couldn't find `Code` here, that would require a small change setting `disable_ligatures`, or else colours would be broken, due to ligatures.
- requirements.txt - add manimpango
- text_mobject.py - use manimpango
Running example scenes should work, no breaking API changes. `register_font` API can be used as
```py
with register_font('roboto.ttf'):
a=Text("Hello Roboto",font="Roboto") …
```

Use ManimPango for Text rendering

---

manimlib/mobject/svg/text_mobject.py

`register_font` method is now available for macOS for `ManimPango>=v0.2.3`, which was released a few days back.
https://github.com/ManimCommunity/ManimPango/pull/26
- Edit doc string

register_font is available for macOS

---

example_scenes.py

My motivation was to make the ease of use better because the class would be properly named.
- The spelling of "Development"

Fix typo in example_scenes.py

---

manimlib/mobject/geometry.py

Elbow is unusable in the master
Fixed the __init__ of Elbow
**Code**:
class ElbowExample(Scene):
elbow = Elbow()
self.add(elbow)
**Result**:
An Elbow is drawn

Fix init of Elbow super class

---

.github/workflows/docs.yml

https://github.com/ManimCommunity/ManimPango/issues/53
Install Pango before installing ManimPango, so that docs build.

CI: install pango so that manimpango install

---

manimlib/window.py

https://github.com/3b1b/manim/issues/1509 is caused by Camera.pixel_coords_to_space_coords using the default pyglet window size (1280x720) instead of the actual window size. Fixed by passing the window size to the constructor of PygletWindow.

fix issue #1509

---

manimlib/shaders/inserts/finalize_color.glsl
manimlib/shaders/surface/frag.glsl
manimlib/shaders/textured_surface/frag.glsl
manimlib/shaders/true_dot/frag.glsl

- `camera_distance` is set to be 6 and doesn't change with the `focal_distance`.
- The z coordinate is used to check whether the surface is facing the camera. It generates the wrong result which is particularly obvious when `focal_distance` is small.
- Replace `float camera_distance = 6;` with `float camera_distance = focal_distance;`, and add `uniform float focal_distance;` in some shaders.
- Use the dot product to check whether the surface is facing the camera.
**Code**:
```python
CONFIG = {
"camera_class": ThreeDCamera,
"camera_config": {
"focal_distance": 0.5,
"light_source_position": [1, 1, -2],
"frame_config":{
"frame_shape": (4, 3),
}
}
}
sphere = Sphere(radius=2)
sphere.shift(DOWN*3.3)
sphere.set_color('#cccccc') …
```

Modified the shaders slightly

---

manimlib/mobject/svg/tex_mobject.py

When pattern is an empty string, text is splited one by one. If there is a "$" letter, latex will try to find another "$".

fix issue #1480

---

manimlib/mobject/svg/text_mobject.py

`Text` wasn't scaled correctly previous with https://github.com/3b1b/manim/pull/1383
Closes #1497.
Closes #1533.
Change `TEXT_MOB_SCALE_FACTOR` value
Also deprecate `size` parameter
Also, now text isn't scaled when increasing font size
instead it is passed to the underlying enging
for handling. Though always a Text object is scaled
with a default value so that it fits the screen.
Locally I get the following with this scene. It would nice if others test this.
**Code**:
```py
ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate …
```

Scale Text Correctly

---

docs/source/development/changelog.rst
example_scenes.py
manimlib/mobject/svg/text_mobject.py

Reverts 3b1b/manim#1543
See: https://github.com/3b1b/manim/pull/1554#issuecomment-864357225 https://github.com/3b1b/manim/pull/1543#discussion_r654749380
```text
[1.] before #1543 × -> #1543 √ (but not a good solution)
[2.] before #1543 × -> #1553 √ 
[3.] before #1543 × -> #1553 √ -> #1543 × (master)
[4.] before #1543 × -> #1553 √ -> #1543 × -> #1554 √ (but not a good solution)
[5.] before #1543 × -> #1553 √ -> #1543 × -> #1555 √ (same as [2.])
```
Closes #1533

Scale `Text` correctly | Revert "Fixed the default size of Text"

---

example_scenes.py
manimlib/mobject/mobject.py

Fixes https://github.com/3b1b/manim/issues/1385 issue (ControlsExample Scene)
1. Add `self.suspend_updating(recurse)` line back to `Mobject.clear_updaters` function
(This was removed back in https://github.com/3b1b/manim/commit/d7f3f5ad24b22ed7bc85ee27df03319498fa863f commit which fixed https://github.com/3b1b/manim/issues/1378 issue)
2. Unrelated to ControlsExample Scene, Remove unused `listen_to_events` `CONFIG` of `Mobject` which I added during Interactive Mobjects development but never used it! (https://github.com/3b1b/manim/pull/1323, https://github.com/3b1b/manim/pull/1326, https://github.com/3b1b/manim/pull/1335)
I am not sure of the consequences of the first change. Since it was intentionally removed before to fix the https://github.com/3b1b/manim/issues/1378 issue, please check …

Fix ControlsExample Scene

---

manimlib/once_useful_constructs/counting.py

Hi,
This is my first attempt at a pull request for manim.
It fixes some runtime errors when generating counting.py (no issue found on the subject).
```
for point in self.get_template_configuration(place)
TypeError: get_template_configuration() takes 1 positional argument but 2 were given
it.cycle(new_template)
NameError: name 'it' is not defined
```
These errors do not appear anymore after fix.
[![Build Status](https://travis-ci.org/Lalourche/manim.svg?branch=fix-counting)](https://travis-ci.org/Lalourche/manim)
Cheers
Lalourche

Fixed execution of counting.py

---

manimlib/mobject/svg/text_mobject.py
manimlib/utils/space_ops.py

From #1331 we can know that the triangulation is sometimes incorrect. #1552 offers a temporary hack for showing text correctly, but it still can't deal with all situations. This pull request aims to fix the bug completely.
I rewrote the function `earclip_triangulation`. The function `earcut` can deal with one polygon with empty holes (without other rings in the hole), so I just deal with the shapes in a hole separately.
Also, I removed the temporary hack in `text_mobject.py`.
It runs almost as fast as before (before #1552).
**Code**:
```python
import time
class FontTest(Scene):
start=time.time()
chinese_text="疆域 画面 藤蔓 寒颤 回复 困难 \n蛐蛐 量取 魓 圖 轟 畾 體 團 垇 儽"
text1 = Text(chinese_text, font="SimSun").scale(1.3).shift(UP*3)
text2 = Text(chinese_text, …
```

Fix triangulation 

---

manimlib/mobject/svg/text_mobject.py

Add MarkupText which is previously in Community Edition
This would use a Pango specific markup that looks like HTML.
There are some specific implementation here about `<color>`
and `<gradient>`
Pango doesn't support `<gradient>`  or `<color> ` instead it works with `color` attribute and the gradient isn't supported.
Since `SVGMobject` doesn't know about parsing colours from SVG image and implementation of `<color>` and `<gradient>` is added.
- Add a new class MarkupText
Most parts of the code were authored by PhilippImhof and copied from Manim Community. I have added him as co-author in that commit
**Code**:
```py
class TextExample(Scene):
a1 = MarkupText('<span style="italic">italic</span>')
a2 = MarkupText('<span weight="bold">bold</span>')
a3 = MarkupText('<span …
```

Add MarkupText

---

.github/workflows/publish.yml
MANIFEST.in
pyproject.toml
setup.cfg
setup.py

Because manim always use `pbr` for setup, which needs to automatically obtain the version from the `.git/` folder. This leads to the issues of #1390 #1403 that cannot be installed from the `.zip` file.
So I transitioned to the method of using `pyproject.toml` and `setup.cfg` to build, which is also recommended by `setuptools`.
- D `setup.py`
- M `setup.cfg`
- N `pyproject.toml`
- N `MANIFEST.in`
https://test.pypi.org/project/manimgl/

Transition build method to PEP 517

---

manimlib/scene/scene.py

If we add an updater to the frame of the camera, and have not added the frame into the scene before, the updater will not work. So, I suggest to add the frame to the objects of the scene at the initilization stage.

Add frame to the scene when initialization

---

manimlib/scene/scene.py

It's weird that when you Scroll Up, the interactive shell zooms out, this is generally the other way round for most of the UI's.
Simply replace factor -> 1 / factor.

Minor fix for zooming

---

manimlib/mobject/mobject.py

Previous `Mobject.scale` method doesn't use overrided method, which causes some problems when scaling a VGroup:
**Code**:
```python
class Code(Scene):
num = VGroup(
DecimalNumber(1), 
Text("foo")
).scale(4).arrange(RIGHT)
self.add(num)
self.play(num[0].animate.set_value(2))
```
**Output**:
https://user-images.githubusercontent.com/44120331/127976196-03ea964f-3cf5-4260-afa0-6da174f4ce28.mp4
Because `DecimalNumber` override `scale` method to change the `font_size` attribute.
This PR is implemented by recursively calling `scale` method on the submobjects of the current mobject.
- M `manimlib/mobject/mobject.py`: rewrote `scale` method
**Code**:
```python
class Code(Scene):
num = VGroup(
DecimalNumber(1), 
Text("foo")
).scale(4).arrange(RIGHT) …
```

Improve `Mobject.scale`

---

manimlib/mobject/svg/svg_mobject.py

Support the elliptical arc command for SVGMobject. Now all the commands of svg path can be implemented.
This is reached through approximating elliptical arcs with quadratic bezier curves, which is almost the same way to form a circular arc in `Arc` class. The key is to figure out the center of the ellipse, requiring us to solve simultaneous equations. I've built a function `add_elliptical_arc_to(self, rx, ry, x_axis_rotation, large_arc_flag, sweep_flag, point)`, inside which a bunch of functions were defined just to do those calculations. I guess it might be better to transfer them into the file `utils\space_ops.py`, but I daren't make too much changes across files in my first pull request.
Detailed annotations are left in the code. I deduced all those stuff by hand today .(:з」∠). …

Support the elliptical arc command for SVGMobject

---

docs/source/getting_started/example_scenes.rst

Fixed a documentation typo in updatersExample section under Example Scenes section . 
The following change was made in example_scenes.rst file . 
- In line 338 , I have fixed a trivial typo which may mislead the readers  (thst -> that).
No explicit testing was done for a typo fix in  documentation as It'll be reflected as expected without any issues.
**Result**: The typo is fixed for better.

Typo fix in UpdatersExample

---

example_scenes.py

updated the cmd command line to "manimgl example_scenes.py OpeningManimExample" instead of "python -m manim", which the latter one was used for cairo-backend manim version instead of the current manimgl

Update comments in example.py

---

manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py

- To make combining mobjects to a Group of mobjects and adding mobjects to a group more convenient. 
- In file mobject.py, added __add__ function and __mul__ dunder function for Mobject, returning a Group type accordingly
- In file vectorized_mobject,py, added __add__ dunder function
- 
**Code**:
```python
class testscene(Scene):
cir = Circle()
sq = Square()
group1 = (cir*6).arrange_in_grid(2, 3)
print(type(group1))
self.add(group1)
group2 = (cir+sq).move_to(DOWN)
self.add(group2)
print(type(group2))
```
**Result**:
```
<class 'manimlib.mobject.types.vectorized_mobject.VGroup'>
<class 'manimlib.mobject.types.vectorized_mobject.VGroup'>
```

 Overridden add operations for mobjects

---

manimlib/__init__.py
manimlib/mobject/boolean_ops.py
requirements.txt
setup.cfg

Add boolean operations for mobjects
The `boolean_ops.py` contains 4 boolean operations for 2D mobjects, using the package `skia-pathops`. The code is in fact borrowed from the community edition.

Add boolean operations for mobjects

---

manimlib/mobject/probability.py

It's only a minor change. I found out that BarChart() doesn't have an option to add ticks on x-axis. I know it's because the x-axis is usually for names or labels and not values, but I think it's nice to add an option to add ticks to seperate bars for better visualization.
- I looked up at how manim add ticks on y-axis and created an option for people to also add ticks to the x-axis
- I added a config parameter "include-x-ticks"
- The number of ticks divided is also the number of values
**Code**:
```py 
global chart
bar_value = [50]*10
chart = BarChart(
bar_value,
label_y_axis = True,
n_ticks = 10,
max_value = 100,
bar_label_scale_val = 0.5,
include_x_ticks = True
)
self.add(chart)
```
**Result**
:

Add option to add ticks on x-axis in BarChart()

---

example_scenes.py

fixed typo in comments
- remove an extra 'all'
- 
- 
**Code**:
**Result**:

removed extra 'all' from comments

---

manimlib/mobject/svg/brace.py

-When adding a Brace Label, I can adjust the label scale and the buff between the brace and the mobject adding to. However, I can not adjust the buff between the label and the brace, which would make the distance disproportional. 
-Directly using ```brace.scale()``` does not work either, as this will change the length of the brace as well.
-Meanwhile, directly passing in the argument ```buff=value``` as keyword argument will set the buff between the target mobject and the brace only. And since both methods (```Brace.CONFIG``` and ```Brace.put_at_tip```) use the ```buff``` keyword argument, therefore, to allow different values can be passed in for "mobject-brace buff" and "brace-label buff", this parameter is clarified as ```label_buff```.
```python
brace1 = BraceLabel(dl1, 'r', UP, …
```

Adding "label_buff" config parameter for Brace

---

manimlib/mobject/coordinate_systems.py

- After initializing a ```NumberPlane``` object, the code area below will be marked as "unreachable" by Pylance
- This grey out the code and disables syntax highlighting
(When I was writing the code)
(In the source code)
- Meanwhile, when clicking "show definition" for ```get_x_axis()``` or ```get_y_axis```, it will jumps to abstract methods under ```CoordinateSystem```
- https://github.com/microsoft/pylance-release/issues/248 (Reference) 
This warning was due to 
```python 
def get_axes(self):
raise Exception("Not implemented")
``` 
however without adding an abstract class decorator
```python 
@absrtactclass
def get_axes(self):
raise Exception("Not implemented")
``` 
(Jumping was due to the fact that ```get_x_axis()``` and ```get_y_axis``` are not overrode again under ```Axes``` class) …

Fix "Code is unreachable Pylance" warning for NumberPlane

---

manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/types/vectorized_mobject.py

ManimGL only supports `matrix(...)`, `scale(...)`, `translate(...)` transform, and doesn't support multiple transformation in a single `transform` property, which causes many issues.
<details>
<summary>For example</summary>
**Code**:
```python
class Code(Scene):
svg = SVGMobject("formula.svg", stroke_width=0).set_width(13)
self.add(svg)
```
**Result**:
</details> 
This pull request adds full support for all transforms in the [svg standard](https://www.w3.org/TR/css-transforms-1/#svg-syntax), which are `matrix translate scale rotate skewX skewY`.
And refactors the parsing of the name and parameters of each transform by referring to https://github.com/cjlano/svg/blob/3ea3384457c9780fa7d67837c9c5fd4ebc42cb3b/svg/svg.py#L75.
- M`manimlib/mobject/mobject.py`: allow …

Improve handling of SVG transform and Some refactors

---

manimlib/mobject/geometry.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/tex_mobject.py
manimlib/mobject/svg/text_mobject.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py

Before, `SVGMobject` will remove all styles from a svg file.
This pull request parse the style for SVG by refering to [ManimCommunity/manim](https://github.com/ManimCommunity/manim).
In order to prevent the style generated layer by layer in `init_points` from being globally overwritten by the `init_colors` after it. I added a parameter `override` to `init_colors`, which is set to `True` by default (that is, consistent with the original performance), but when `override = False`, it will recurse layer by layer and set the color to the currently generated color.
- M `manimlib/mobject/svg/svg_mobject.py`: add SVG style parser and fix some bugs of path string
- M `manimlib/mobject/types/vectorized_mobject.py`: add `override` parameter to `init_colors`
- M `manimlib/mobject/mobject.py`: …

Parse and generate style for SVG

---

manimlib/mobject/svg/svg_mobject.py
requirements.txt
setup.cfg

https://github.com/3b1b/manim/pull/1717#issuecomment-1022344306
I solved this issue. Use tinycss2 to parse style (including `<style>` tag and `style` attributes in other tags), and use cssselect2 to choose which tag to apply to based on selector.
And in order to make cssselect2 handle selectors correctly, I replaced `xml.dom.minidom` with `xml.etree` for parsing SVG file, which also has more features.
At the same time, I also implemented the processing of the `<line>` tag by the way.
- M `manimlib/mobject/svg/svg_mobject.py`: improve style parsing and implement the `<line>` tag
- M `setup.cfg` & `requirements.txt`: add dependency of `cssselect2`(`tinycss2` will be installed along with it)
**Code**:
```python
class Code(Scene):
svg = SVGMobject("beer.svg", color=BLACK, …
```

Parse style from <style> tag and Add support to <line> tag

---

manimlib/mobject/mobject.py
manimlib/mobject/svg/mtex_mobject.py

- M `manimlib/mobject/svg/mtex_mobject.py`
> Since MTex uses color for indexing submobjects, tex that originally brought with `\color` commands (or `\textcolor`, etc.) will cause failure. So I handled such a situation. Also, I reconstructed the algorithm in `generate_tex()` function, making svg files generated as few as possible.
- M `manimlib/mobject/mobject.py`: remove unused parameter
**Code**:
```python
class MathjaxTest(Scene):
mtex = MTex(
"{\\color{green} R G} {{Y}} B",
tex_to_color_map={"R": RED},
color=BLUE
)
mtex.set_color_by_tex("{{Y}}", YELLOW)
self.add(mtex)
```
**Result**:

Handle explicit color-related commands

---

manimlib/mobject/boolean_ops.py

https://github.com/3b1b/manim/pull/1711
solution full credits to @widcardw
Just helping to upload this
```python
class DifferenceExample(Scene):
cir1 = Circle(radius=3).move_to(LEFT * 1.5)
cir2 = cir1.copy().move_to(RIGHT * 1.5)
d = Difference(cir1, cir2, color=YELLOW, fill_opacity=0.4)
self.add(cir1, cir2, d)
```
```python
class ExclusionExample(Scene):
cirs = VGroup(*[
Circle(radius=2).move_to(1.5 * np.array([
np.cos(i / 3 * TAU), np.sin(i / 3 * TAU), 0
])) for i in range(3)
])
e = Exclusion(*cirs, color=YELLOW, fill_opacity=0.4)
self.add(cirs, e)
```
```python 
class IntersectionExample(Scene):
cir1 = Circle(radius=3).move_to(LEFT * 1.5)
cir2 = cir1.copy().move_to(RIGHT * 1.5)
i = Intersection(cir1, cir2, color=YELLOW, …
```

Temporarily fix boolean operation bug

---

requirements.txt
setup.cfg

- remove `argparse` because it is a built in module
- remove `pyreadline` as it is no longer needed and does not work with python 3.9+
- add classifiers to package metadata

Clean dependencies

---

manimlib/animation/transform_matching_parts.py
manimlib/mobject/svg/mtex_mobject.py

This is (possibly) the last overall refactoring applied to MTex class. The structure is updated to prevent from polluting namespace, and some algorithms of methods are improved.
There are some small difference between this version and former pull requests. For example,
- Color-related commands, from now on, are not allowed since they are really tricky to hangle in MTex;
- Substrings specified are stripped;
- Whitespaces and "\_", "^" can be skipped when matching tex (you can match "a b" if "a" and "b" are isolated);
- Tex strings of submobjects are formatted so that they can be matched more easily.
Also, the class `TransformMatchingMTex` is implemented. It tries to match as long and complete strings as possible. Hope this would be helpful :) 
**Relative methods**
```python …
```

Refactor MTex and implement TransformMatchingMTex

---

manimlib/mobject/functions.py
requirements.txt
setup.cfg

Implement `ImplicitFunction` class using `isosurfaces` package. This is borrowed from manim community edition.
- M `manimlib/mobject/functions.py`: implement ImplicitFunction
- M `requirements.txt`: add dependency
- M `setup.cfg`: add dependency
**Code**:
```python
class FuncTest(Scene):
graph = ImplicitFunction(
lambda x, y: x * y ** 2 - x ** 2 * y - 2,
color=YELLOW
)
self.add(NumberPlane(), graph)
```
**Result**:

Implement ImplicitFunction

---

manimlib/scene/scene.py

Change the keyboard shortcut to drop into an ipython terminal embedding from interactive mode to be "ctrl + shift + e".

Change interaction-to-embed keybinding

---

manimlib/mobject/functions.py

Sometimes a graph is initialized with ```get_graph``` method, which stores the function into ```self.underlying_function``` attributes. While for function graphs, they are stored in ```self.function``` attribute.
Reorganizing getters can help to avoid Attribution error, when trying to initialize another graph that shares the same function with an existing graph.

Reorganize getters for ParametricCurve

---

docs/source/documentation/constants.rst
manimlib/constants.py
manimlib/mobject/svg/mtex_mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/tex_mobject.py
manimlib/mobject/svg/text_mobject.py

Resolve conflicts of #1736 and #1751, and adjust some typings. 
- M `docs/source/documentation/constants.rst`: remove `START_X`, `START_Y` constants
- M `manimlib/constants.py`: remove `START_X`, `START_Y` constants
- M `manimlib/mobject/svg/mtex_mobject.py`: adjust typings
- M `manimlib/mobject/svg/svg_mobject.py`: remove unused method `get_mobject_from`
- M `manimlib/mobject/svg/text_mobject.py`: add type hints; remove an unused import

Adjust some typings

---

manimlib/utils/space_ops.py

Manim does not provide feedback to the user while processing a long-running SVG mobject.
Since manim typically runs so fast, a long-running SVG catches the user by surprise. Personally it took me a few hours to figure out that manim was not freezing, rather it was just taking a long time on a complicated SVG.
This change gives the user some feedback while processing a complicated SVG.
Specifically:  
If the SVG has over 100 rings to process, we display a counter to log.info once per 100 processed rings.  Thus the user learns manim is working on a long-running operation.
If the SVG has under 100 rings, this change has no effect. Manim will process it quick enough.
**Code**:
I tested with the Noto emoji - Afghan flag SVG.  Here is the complete scene code, which automatically gets the SVG …

Give the user feedback for SVGs that take a while

---

manimlib/mobject/numbers.py
manimlib/mobject/svg/labelled_string.py
manimlib/mobject/svg/mtex_mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/text_mobject.py

Some refactors on `LabelledString` and relevant classes.
- M `manimlib/mobject/numbers.py`: Remove the cache dict, since `SVGMobject`s are already cached.
- M `manimlib/mobject/svg/labelled_string.py`: Support passing in `svg_default.color` and `svg_default.fill_color` as aliases of `base_color`; improve algorithm.
- M `manimlib/mobject/svg/mtex_mobject.py`: Some refactors.
- M `manimlib/mobject/svg/text_mobject.py`: Some refactors.
- M `manimlib/mobject/svg/svg_mobject.py`: Add an empty line.

Refactor `LabelledString` and relevant classes

---

manimlib/mobject/svg/labelled_string.py
manimlib/mobject/svg/mtex_mobject.py
manimlib/mobject/svg/text_mobject.py

Add support for `substring` and `case_sensitive` parameters for `LabelledString.get_parts_by_string` method, and other relative methods as well.
- M `manimlib/mobject/svg/labelled_string.py`
- M `manimlib/mobject/svg/mtex_mobject.py`
- M `manimlib/mobject/svg/text_mobject.py`

Add support for `substring` and `case_sensitive` parameters

---

manimlib/mobject/svg/tex_mobject.py

Makes something like `Tex("\overset", "{def A}", "{=}")` work.
Added `"\\overset"` -> `"\\overset{\\quad}{\\quad}"` and documented why \frac and friends do not work (yet).
**Code**:
```python
color = {"isolate": ["{A}", "{B}"], "tex_to_color_map": {"{A}": GREEN, "{B}": BLUE}}
t = Tex(r"a{B}c", r"\overset", "{A}{=} a{B}c", **color)
self.play(Write(t))
```
**Result**:

Added a \overset as a special string

---

manimlib/animation/creation.py
manimlib/animation/transform_matching_parts.py
manimlib/mobject/svg/labelled_string.py
manimlib/mobject/svg/mtex_mobject.py
manimlib/mobject/svg/text_mobject.py

There's a bug when dealing with multi-line tex. Just fixed.
- M `manimlib/animation/creation.py`: use attribute instead of calling a method
- M `manimlib/animation/transform_matching_parts.py`: clean up logic
- M `manimlib/mobject/svg/labelled_string.py`: fix bug; add `regex` parameter for `get_parts_by_tex` method; remove `indices_of_part` and `indices_lists_of_parts` methods
- M `manimlib/mobject/svg/mtex_mobject.py`: some small refactors
- M `manimlib/mobject/svg/text_mobject.py`: some small refactors

Fix bug when handling multi-line tex

---

manimlib/mobject/types/image_mobject.py

Fixes #1790.
Because `set_color` of `ImageMobject` actually does nothing, I override it to just return itself to avoid #1790.

Fix `ImageMobject` by overriding `set_color` method

---

manimlib/mobject/geometry.py
manimlib/mobject/probability.py
manimlib/mobject/types/point_cloud_mobject.py
manimlib/scene/interactive_scene.py

Add some missed imports
- M `manimlib/mobject/geometry.py`: import `DEGREES`, `Iterable`
- M `manimlib/mobject/probability.py`: import `numpy`
- M `manimlib/mobject/types/point_cloud_mobject.py`: import `numpy`

Add necessary imports

---

manimlib/mobject/svg/string_mobject.py

There's a logistic bug when handling `None` in spans. My apologies for that.
- M `manimlib/mobject/svg/string_mobject.py`

Fix a logistic bug

---

manimlib/animation/transform.py
manimlib/mobject/mobject.py

With the pr of manim community, we can easily use `.animate` method to build Animation, but we cannot change the arguments of Animations. With the `set_anim_args` method, we can change args of Animation. Since `_AnimationBuilder` will build it into `MoveToTarget`, we can also use `path_arc` or `path_func` and so on.
```python
class TestAnimateArgs(Scene):
def construct(self) -> None:
a = Circle().to_edge(LEFT)
anim_builder = (
a
.animate
.scale(3)
.to_edge(RIGHT)
.set_anim_args(run_time=3, time_span=(1, 2), rate_func=double_smooth, path_arc=PI/2)
)
self.play(anim_builder)
```
https://user-images.githubusercontent.com/55699713/189510867-2d94d2c5-f8bc-44ed-a3e4-697df835cea4.mp4

Add `set_anim_args` to `.animate` method

---

docs/source/getting_started/example_scenes.rst
example_scenes.py

I fixed a typo in the documentation
I fixed a single typo "termnial" in the documentation.
It is a documentation change

Fixing a typo ("termnial" -> "terminal")

---

manimlib/extract_scene.py

I've noticed that if no scene names are passed to `manimgl` explicitly, then the rendering progress bar will not be shown correctly.
To showcase the bug, suppose we have a file with only one Scene class in it:
```python
def MyScene(Scene):
```
And I'd like to render it using `manimgl`. Then both of the following command line should work:
```bash
$ manimgl my_scene.py MyScene -w
$ manimgl my_scene.py -w
```
as there's only one scene in the file and the scene name can be omitted.
But when I omit the scene name(second case), the progress bar by `SceneFileWriter` during rendering will disappear/can't show correctly, which is annoying you're rendering long and intricate scenes.
Fix the bug with rendering progress bar as shown above.
I believe that this is a bug. But if …

Fix bug with rendering progress bar

---

manimlib/animation/animation.py

In manim cairo-backend, line 127 and 131,
Fixing typo: "ipmlemented" to "implemented" ; "understanable" to "understandable"

Fix 2 typos

---

manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py
manimlib/utils/space_ops.py

When using `tqdm` in the context of Jupyter Notebooks, the CLI version does not cut it.
For this reason, the `tqdm` authors created the `tqdm.auto` dispatching, which displays an optimal version of `tqdm` for either CLI or jupyter notebooks depending on the context.
Using the package in a CLI or Jupyter Notebook environment will display a different loading bar.

Updated tqdm to support also notebooks

---

manimlib/mobject/types/vectorized_mobject.py

The type union operator wasn't added until Python 3.10. This was added a few days ago, which caused manim to crash with a TypeError for earlier versions of Python. This CL causes the code to do the same thing, but it works for <3.10 versions of Python too.
Fixes #1968

Make isinstance check work for python 3.7-3.9

---

manimlib/animation/fading.py
manimlib/camera/camera.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_fill/geom.glsl
manimlib/shaders/quadratic_bezier_fill/vert.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl

There have been many issues associated with triangulating VMobjects to illustrate their fill. Transforms between VMobjects with fill often show strange triangulation artifacts and can be laggy when the triangulation needs to be recomputed on each frame.
This change introduces a mode that obviates the need for such a triangulation and makes it the default. It's essentially based on [this blog post](https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac), and makes use of blending signed alpha values to effectively compute the winding number of a curve around each pixel.
Filled VMobjects are given a separate rendering pass to a texture using a specific blending mode, which is then blended with the rest of the scene using default alpha blending.
It may cause …

Winding fill

---

manimlib/animation/animation.py
manimlib/animation/creation.py
manimlib/animation/transform.py
manimlib/camera/camera.py
manimlib/camera/camera_frame.py
manimlib/config.py
manimlib/mobject/mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/types/dot_cloud.py
manimlib/mobject/types/image_mobject.py
manimlib/mobject/types/point_cloud_mobject.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/interactive_scene.py
manimlib/scene/scene.py
manimlib/scene/scene_file_writer.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/shaders/quadratic_bezier_fill/geom.glsl
manimlib/utils/shaders.py
manimlib/window.py

Move the rendering logic away from camera.py and instead move it into the shader wrappers. Previously camera would keep track of which mobjects were actively changing and store a nebulously named dictionary called "render_group" to keep track of data buffers that didn't need to be regenerated. Now, a Mobject will keep track of whether its data has been changed, and buffers are only repopulated as they need to be, without the need for Scene to periodically call "refresh_static_mobjects".
Additionally, this contains a (mildly hacky) fix to ensure that the new fill rendering mode introduced in https://github.com/3b1b/manim/pull/1972 has expected behavior with respect to alpha blending.

Refactor render out of camera (plus winding fill blending fix)

---

manimlib/mobject/changing.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/geometry.py
manimlib/mobject/matrix.py
manimlib/mobject/mobject.py
manimlib/mobject/numbers.py
manimlib/mobject/shape_matchers.py
manimlib/mobject/types/dot_cloud.py
manimlib/mobject/types/point_cloud_mobject.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/mobject/value_tracker.py
manimlib/typing.py
requirements.txt

In response to @TonyCrane's [suggestion](https://github.com/3b1b/manim/pull/1981#issuecomment-1413882723)

Use typing_extensions to import Self for python versions <3.11

---

manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_fill/frag.glsl
manimlib/utils/shaders.py

This fixes some issues with alpha-blending when using winding fill, namely strange shadow effects when something with higher opacity is blended one something with lower opacity. In doing so, it offers a cleaner approach to the whole algorithm, essentially just using a certain alpha blending function, which makes it no longer necessary to clear the fill canvas with a negative color.

Cleaner winding fill

---

manimlib/animation/fading.py
manimlib/animation/growing.py
manimlib/animation/transform.py
manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py

- Don't copy Transform.target_mobject if it already aligns with Transform.mobject
- Lock uniform keys, analogous to how data keys lock, during Transform
- Use resize_points in Mobject.set_data (which in turns makes sure outer_vert_indices are always correct)

Several minor fixes

---

docs/source/getting_started/installation.rst

Hi Team Manim
Hi, I am Rudransh Bharwdaj a developer. When I was making some project I face many problem while installing ffmpeg and I realized that many other developers are also facing this issue so I added how to install ffmpeg for windows, macos, and linux.
If there is any correction please tell me i will solve it .
Thank you
Excited for SoME3

Update installation.rst added FFmpeg install

---

example_scenes.py

When running `manimgl example_scenes.py OpeningManimExample` I noticed: there is no **include_background_rectangle** argument in **IntegerMatrix** class, so I removed it. Otherwise, it will raise an error.
`IntegerMatrix(matrix, include_background_rectangle=True) --> IntegerMatrix(matrix)`
Launched `manimgl example_scenes.py OpeningManimExample`. No errors.

remove include_background_rectangle

---

manimlib/camera/camera.py
manimlib/scene/scene.py
manimlib/utils/shaders.py
manimlib/window.py

Previously, during interactive development, rendering would happen continuously regardless of whether the scene was animating or being interacted with. This change has the scene only render in this mode when it needs to.

Energy savings

---

manimlib/animation/animation.py
manimlib/animation/composition.py
manimlib/animation/creation.py
manimlib/animation/numbers.py
manimlib/animation/transform.py
manimlib/camera/camera.py
manimlib/event_handler/event_dispatcher.py
manimlib/mobject/geometry.py
manimlib/mobject/interactive.py
manimlib/mobject/mobject.py
manimlib/mobject/mobject_update_utils.py
manimlib/mobject/numbers.py
manimlib/mobject/probability.py
manimlib/mobject/types/surface.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/scene/scene.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier_stroke/frag.glsl
manimlib/shaders/quadratic_bezier_stroke/geom.glsl
manimlib/shaders/quadratic_bezier_stroke/vert.glsl
manimlib/utils/shaders.py

Changes to the defaults for border width.
Now, fill antialiasing happens using multisample antialiasing, and by default there is no border width. For text and tex, that default is set to 0.5 to add a hint of boldness.
This PR also includes: 
- A quick fix to not pause while skipping ahead in animations
- A bug fix for the case of narrowing to a stroke width of zero

Adjustments to fill antialiasing

---

manimlib/animation/animation.py
manimlib/animation/rotation.py

`time_span` doesn't work for animations of mobjects with submobjects, such as `DashedLine`.
像 `DashedLine` 这样含有多个子物件的图形的动画无法正确处理 `time_span`。
- add method `time_spanned_alpha` in `Animation` to calculate the animation progress instead of changing `rate_func` when `begin` is called
在 `Animation` 类中添加了计算动画进度的方法 `time_spanned_alpha`，专门用来计算存在 `time_span` 时的动画进度，而不在调用 `begin` 时改变 `rate_func`
- since `Rotating` also uses `rate_func` to decide the animation progress in `interpolate_mobject`, changes of `rotation.py` are made to correspond
由于 `Rotating` 类的 `interpolate_mobject` 也是用 `rate_func` 计算动画进度，为了保持一致还修改了 `rotation.py`
**Code / 代码**:
```python
class TestScene(Scene):
def construct(self) -> None:
self.play(ShowCreation(Line((-1, 1, 0), (-1, -1, 0)), time_span=(0, 2)), …
```

fix(animation): `time_span` doesn't work for mobjects with submobjects

---

manimlib/utils/rate_functions.py

I find a bug when using `there_and_back_with_pause`.
fix the behaviour of `there_and_back_with_pause` when setting `pause_ratio` with other values.
**Code**:
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
def smooth(t: float) -> float:
s = 1 - t
return (t**3) * (10 * s * s + 5 * s * t + t * t)
def there_and_back_with_pause(t: float, pause_ratio: float = 1.0 / 3) -> float:
a = 1. / pause_ratio
if t < 0.5 - pause_ratio / 2:
return smooth(a * t)
elif t < 0.5 + pause_ratio / 2:
return 1
else:
return smooth(a - a * t)
def there_and_back_with_pause_corrected(t: float, pause_ratio: float = 1. / 3) -> float:
a = 2. / (1. - pause_ratio)
if t < 0.5 - pause_ratio / 2:
return smooth(a * t)
elif t < 0.5 + pause_ratio / 2:
return 1
else:
return smooth(a - …
```

fix: `there_and_back_with_pause`

---

requirements.txt

I opened cmd and typed `manimgl`, as expected, a window was created. However, while typing any python code in the shell, the following error was raised:
While digging into the issue, i found that the manim library is not compatible with some versions of IPython (i got the error with version 8.14.0 and 8.16.0).
a past [question ](https://stackoverflow.com/questions/76519814/manim-community-interactive-embed-causes-ipython-curruption-sqlite3-progra)at stackoverflow also confirmed the same. 
The solution was to simply upgrade IPython to the latest version `pip install ipython --upgrade` 
- Changed requirements.txt to include `ipython>=8.18.0`. This makes sure that the compatible version of ipython is installed with the manimgl library.
open cmd and type `pip install ipython==8.14.0`.
after …

Modifying requirements.txt to include the latest version of IPython.

---

manimlib/mobject/types/image_mobject.py

Triggered when rendering the same texture consecutively.
Mobject default render mode is TRIANGLE_STRIP, which will outputs extra triangles;
Use TRIANGLES mode and add vertices to fix this.
- image_mobject.py
**Code**:
```python
image = ImageMobject("res/bili.png").scale(0.2)
a = Group(*[image.copy() for _ in range(25)]).arrange_in_grid(5, 5)
self.add(a)
```
**Result**:

Error effect when rendering the same ImageMobject

---

manimlib/animation/indication.py

Animation VShowPassingFlash often encounters an IndexError: index 0 is out of bounds for axis 0 with size 0.
for example:
```python
class Video(Scene):
s = TexText(r"A",template="tex")
self.play(ShowCreation(s))
self.play(VShowPassingFlash(s))
```
The error message is as follows:
File "test.py", line 9, in construct
self.play(VShowPassingFlash(s))
File "manimlib/scene/scene.py", line 405, in wrapper
func(self, *args, **kwargs)
File "manimlib/scene/scene.py", line 661, in play
self.begin_animations(animations)
File "manimlib/scene/scene.py", line 616, in begin_animations
animation.begin()
File "site-packages/manimlib/animation/indication.py", line 227, in begin
super().begin()
File "manimlib/animation/animation.py", line 79, in begin …

fix VShowPassingFlash index out of bounds issue

---

manimlib/mobject/mobject.py
manimlib/scene/scene.py

[Suggestion: Using z-order to define layer for Mobjects.](https://github.com/3b1b/manim/issues/852)
- mobject.py
- scene.py
- 
**Code**:
```python
class Video(Scene):
s = Square(zorder=1).set_fill(RED,opacity=1)
c = Circle(zorder=2).set_fill(BLUE,opacity=1)
t = Triangle(zorder=0).scale(2).set_fill(GREEN,opacity=1)
r = Rectangle(width=4,height=2,zorder=0).set_fill(PINK,opacity=1)
self.play(ShowCreation(c))
self.play(ShowCreation(s))
self.play(ShowCreation(t))
self.play(ShowCreation(r))
```
**Result**:
https://github.com/3b1b/manim/assets/15604323/cc51b03b-db30-41ea-8050-9e00922151fa

add zorder to mobject

---

manimlib/animation/animation.py

In the Animation class, the `get_all_mobjects_to_update` method would cause duplicate Mobjects to be returned, and update was performed on all of them.
Add `items = list(set(items))` in the `get_all_mobjects_to_update` method of the Animation class to achieve the purpose of removing duplicate items.
```
class AnimationIssue(ThreeDScene):
def construct(self) -> None:
day_texture = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Whole_world_-_land_and_oceans.jpg/1280px-Whole_world_-_land_and_oceans.jpg"
night_texture = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/The_earth_at_night.jpg/1280px-The_earth_at_night.jpg"
sphere = Sphere(radius=RADIUS)
surface = TexturedSurface(sphere, day_texture, night_texture)
always_rotate(surface)
self.play(FadeIn(surface, …
```

Remove duplicate items

---

manimlib/utils/bezier.py

I noticed that the the indices go beyond the length of the `anchors`.

Correction of indices

---

manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/shader_wrapper.py
manimlib/shaders/quadratic_bezier/depth/geom.glsl
manimlib/shaders/quadratic_bezier/depth/vert.glsl
manimlib/shaders/quadratic_bezier/fill/geom.glsl
manimlib/shaders/quadratic_bezier/fill/vert.glsl
manimlib/shaders/quadratic_bezier/stroke/geom.glsl
manimlib/shaders/quadratic_bezier/stroke/vert.glsl

Attempt to fix https://github.com/3b1b/manim/issues/2166

Remove use of gl_VertexID

---

manimlib/scene/scene.py

When the time intervals are (0, dt, 2dt, ...), during the first frame processing, only the video is inserted, but the update parameter is 0, which causes scene.time to be inaccurate. The correct time intervals should be (dt, 2dt, ...)
- 
- 
- 
**Code**:
**Result**:

Update scene.py to make scene.time more accurate

---

manimlib/scene/scene.py

The motivation is the variable scope problem mentioned in the _How I animate 3Blue1Brown | A Manim demo with Ben Sparks_ video.
This is what's going on:
```python
>>> source_code = """
... x = 9
... def f():
...   print(x)
... f()
... """
>>> namespace = {}
>>> exec(source_code, namespace, namespace)
9
>>> exec(source_code, {}, {})
File "<stdin>", line 1, in <module>
File "<string>", line 5, in <module>
File "<string>", line 4, in f
NameError: name 'x' is not defined
>>> 
```
When you run `exec` (or `eval`), those two last arguments are a globals namespace and a locals namespace. The `x = 9` line modifies the locals namespace, but the `print(x)` line inside the function reads from the globals namespace. We need them to be the same.
When IPython runs our …

Fix `NameError` when a pasted function attempts to access a variable in its outer scope

---

manimlib/camera/camera.py

When using ManimGL in preview mode, the window background color was always Black irrespective of what `background_color` is specified in the `config` file
Changed `self.window.clear` in `camera.py` file.

Minor Bug fixed: window's bg color now changing.

---

manimlib/scene/scene.py
manimlib/window.py

When working in the interactive mode, the OpenGL window might be hidden behind other programs. Therefore, we introduce a new `focus()` command here to focus the window. This could also be very beneficial to our [`Manim Notebook`](https://github.com/Manim-Notebook/manim-notebook) VSCode extension (in construction) allowing to automatically focus when previewing a Manim Cell.
- Add a `focus()` method to the scene.
- Implement the focus mechanism in the window.
Unfortunately, the pyglet [`activate()`](https://pyglet.readthedocs.io/en/latest/modules/window.html#pyglet.window.Window.activate) method did not work for me (using WSL) while the proposed solution works, but produces a small flickering and also offsets the window by a small amount in the upper left direction. Maybe you know a better …

Add `focus()` command

---

manimlib/constants.py
manimlib/scene/interactive_scene.py
manimlib/scene/scene.py

Modifier keys are given by Pyglet with bitmasks, however the checks were done by equality comparison. Also, the checks were only done for Mac users (COMMAND key) and not the CTRL command. In case the user had the NUM_LOCK or CAPS_LOCK or any other modifier key turned on, then the checks completely failed and nothing was interactive.
- Change the checks with the `&` operator.
- Add both `COMMAND` and `CTRL` checks
- Properly get the modifier constants from the Pyglet library instead of hardcoding them
- Remove the old hardcoded now unused modifier constants
**Code**:
```py
import numpy as np
class TestScene(InteractiveScene):
circle = Circle(radius = 2)
self.play(DrawBorderThenFill(circle))
```
Run the simple interactive scene and test if all …

Properly check modifier keys.

---

manimlib/mobject/coordinate_systems.py

As it stands, `get_riemann_rectangles` raises an error when called. It is using a keyword arg named `stroke_background` when internally calling `set_style`, but it does not exist.
In order to preserve the interface of `get_riemann_rectangles`, I've just renamed the keyword arg when it calls `set_style`, using the expected one `stroke_behind`.
**Code**:
```
axes = Axes()
graph = axes.get_graph(lambda x: x)
rectangles = axes.get_riemann_rectangles(graph)
```
**Result**:
It works fine. Prior to the change, it would raise an error
```bash
TypeError: VMobject.set_style() got an unexpected keyword argument 'stroke_background'
```

Incorrect arg injection in get_riemann_rectangles

---

manimlib/__init__.py
manimlib/config.py
manimlib/constants.py
manimlib/default_config.yml
manimlib/extract_scene.py
manimlib/mobject/shape_matchers.py
manimlib/mobject/svg/old_tex_mobject.py
manimlib/mobject/svg/string_mobject.py
manimlib/mobject/svg/svg_mobject.py
manimlib/mobject/svg/tex_mobject.py
manimlib/mobject/svg/text_mobject.py
manimlib/reload_manager.py
manimlib/scene/scene.py
manimlib/shader_wrapper.py
manimlib/utils/cache.py
manimlib/utils/customization.py
manimlib/utils/directories.py
manimlib/utils/file_ops.py
manimlib/utils/init_config.py
manimlib/utils/simple_functions.py
manimlib/utils/tex_file_writing.py
manimlib/window.py
requirements.txt

Previously, in generating Tex and Text mobjects, manim would write to and read from various svg files on disk, to prevent the need to regenerate that data on each run, which is especially relevant in rendering LaTeX.
With this PR, we instead use the cache functionality from the disk_cache library to locally cache the relevant svg strings. This makes it easier to consolidate code, and to clear the cache or limit how much disk space it uses.
This also involved refactoring SVGMobject to optionally take in an svg_string, and to update Tex and Text accordingly.
---
Separately, this PR also includes a fair bit of cleaning up for within config.py.  It remains somewhat messy, in particular it's very ambiguous what "config" exactly refers to throughout, but this is an attempt to simply how the …

Cleaner local caching of Tex/Text data, and partially cleaned up configuration

---

manimlib/mobject/boolean_ops.py
manimlib/mobject/svg/tex_mobject.py
manimlib/mobject/svg/text_mobject.py
manimlib/mobject/types/vectorized_mobject.py

While creating the temporary svg file in `text_mobject.py`, Cairo throws an error `b'error while writing to output stream'` on Windows OS.
To avoid that, `delete=False` should be passed in `NamedTemporaryFile` function of the `tempfile` package.
Also, minor cleaning up the imports.

Fixing a Cairo Bug on Windows OS

---

docs/source/getting_started/configuration.rst
manimlib/config.py
manimlib/default_config.yml
manimlib/scene/scene_embed.py

Adapting https://github.com/3b1b/manim/pull/2252 by @Splines after recent refactor.

Autoreload v2

---

docs/source/documentation/constants.rst
docs/source/getting_started/example_scenes.rst
example_scenes.py
manimlib/animation/indication.py
manimlib/animation/transform.py
manimlib/camera/camera_frame.py
manimlib/config.py
manimlib/constants.py
manimlib/default_config.yml
manimlib/extract_scene.py
manimlib/mobject/coordinate_systems.py
manimlib/mobject/geometry.py
manimlib/mobject/matrix.py
manimlib/mobject/mobject_update_utils.py
manimlib/mobject/svg/text_mobject.py
manimlib/mobject/types/vectorized_mobject.py
manimlib/module_loader.py
manimlib/scene/interactive_scene.py
manimlib/scene/scene.py
manimlib/scene/scene_embed.py
manimlib/scene/scene_file_writer.py
manimlib/utils/dict_ops.py
manimlib/utils/file_ops.py
manimlib/utils/simple_functions.py
manimlib/utils/tex.py

- Move keybindings to config
- Ensure temporary svg paths for Text are deleted
- Replace DEGREES constant with more succinct DEG
- Remove several no-longer-used functions
- Add preview_frame_while_skipping to scene config

Misc. clean up

---

manimlib/scene/scene_embed.py

Addressing https://github.com/3b1b/manim/issues/2272
Previously, CheckpointManager.checkpoint_states was shared across multiple instances, which caused issues after reloading. It should be unique to each instance.

Fix checkpoint paste after reload

---

manimlib/window.py

Somewhat confusingly, the window viewport can get offset on initialization, and on reload, in a way that simply resizing the window (even to its current size) fixes.
Previously I had added this to Window.focus, while also calling focus in Window.init_for_scene.  Better is to not necessarily focus on init, and to put the sync line in there directly.  This should partially address the annoyance in https://github.com/3b1b/manim/issues/2271

Move resizing out of Window.focus, and into Window.init_for_scene

---

docs/source/getting_started/configuration.rst
manimlib/scene/scene_embed.py

In response to https://github.com/3b1b/manim/issues/2275
When --autoreload is set, during the interactive mode, before each cell execution the user's module will be reloaded.
@Splines, is this what you had in mind? At the moment I removed the calls to shell.magic("autoreload all") because it feels like this accomplishes the same, but it's very possible I'm missing something.

Have autoreload update shell namespace with reloaded module variables

---

manimlib/default_config.yml
manimlib/extract_scene.py
manimlib/mobject/probability.py
manimlib/mobject/svg/string_mobject.py
manimlib/mobject/svg/text_mobject.py

Whenever some user passes the command `-e <line_number>`, it feels redundant to specify the class name.
The closest class name (above the specified `<line_number>`) should automatically be identified by the program, and updates the value of `scene_names` key in the `run_config` dict.
I couldn't find a better position to insert the code than in the `insert_embed_line_to_module` function. As it ensures that the `scene_names` updates only when the `e` flag is passed, and also the module lines can be used to determine the class name.
Also, resolving minor bugs in `text_mobject` and `string_mobject` files.

Automatically identify the class name based on the specified line number.

---

manimlib/config.py

I'm using a variety of frame rates, and it's inconvenient to change the value in `default_config` each time.
Fixed type conversion for the `--fps` argument as an integer to improve convenience.
**Code**:
Ran the command `manimgl example.py SceneName --fps 240`
**Result**:
The fps value is now passed as an integer without any errors, making it easier to adjust frame rates dynamically.

Fix --fps type conversion to int

---

requirements.txt
setup.cfg

There are dependencies not specified in `setup.cfg` and `requirements.txt`.
Add them.
`python -m pip install -e . && run`

Add missing dependencies to setup.cfg and requirements.txt

---

manimlib/mobject/number_line.py

Fix the issue that changes in `decimal_number_config["font_size"]` get rewritten by `number_config`
When working with `NumberLine` in manim v1.7.2, I found that the decimal number label's size doesn't change with different `font_size` setting.
Swaping the position of `self.decimal_number_config` and `number_config` in `merge_dicts_recursively`.
(Which gives `self.decimal_number_config` a higher priority, fixing the issue.)
**Code**:
```python
class BugDemo(Scene):
NumberLines = VGroup(
NumberLine(decimal_number_config=dict(num_decimal_places=0, font_size=48), include_numbers=True),
NumberLine(decimal_number_config=dict(num_decimal_places=0, font_size=36), include_numbers=True),
NumberLine(decimal_number_config=dict(num_decimal_places=0, font_size=24), …
```

Fix issues in number_line.py that changes in decimal_number_config["font_size"] get rewritten by number_config

---

manimlib/mobject/coordinate_systems.py
manimlib/mobject/mobject.py
manimlib/mobject/number_line.py

1. If `unit_tex` is specified in coordinate labels, "1" is now omitted on both positive and negative axis.
2. While setting the color using rgba (or rgb) func, performance can be improved by assinging colors to all points at once (using NumPy indexing) instead of iterating through them.
However, this change would break the existing code for users who rely on rgba (or rgb) function to set colors for rendering animations.

Performance improved in `set_color_by_rgba_func`

---

manimlib/mobject/svg/svg_mobject.py

Handling arcs in `VMobjectFromSVGPath` is currently flawed. It works well when there is no matrix transformation in the SVG, but when such transformations are present, the behavior becomes problematic. The following comparison illustrates the issue (see the raw SVG file in the **Test** section):
| VS Code | Manim |
|-----------------------|-----------------------|
| ![image](https://github.com/user-attachments/assets/c18418a8-0029-440b-9190-a3e33f5575f5) | ![image](https://github.com/user-attachments/assets/b63094ac-716e-49f6-ab9a-6a1715306f83) |
When opening the SVG file in VS Code, the expected rendering is shown on the left, whereas the right image shows the distorted result rendered by Manim. The issue mainly affects the "wing" part of the SVG.
Based on my analysis, this problem is …

Fix arc handling for `VMobjectFromSVGPath` when a matrix transform is present in the SVG

---

manimlib/animation/fading.py
manimlib/mobject/mobject.py
manimlib/mobject/types/vectorized_mobject.py

Fix error when using `VFadeIn` (and its subclasses).
The `VFadeIn` animation uses `.set_stroke` and `.set_fill` (see: [source](https://github.com/3b1b/manim/blob/f4737828f65999252c0cab9824d9d34cfabf4341/manimlib/animation/fading.py#L166-L171)), but these methods cause an error when the `opacity` is of type `np.float32`. This happens because `np.float32` is handled differently from a regular `float`.
**Note:**  
In `VFadeIn.interpolate_submobject`, the `.set_stroke` and `.set_fill` methods receive `opacity` values from `.get_stroke_opacity` and `.get_fill_opacity`, which return `np.float32`, and this causes the error.
1. Add `np.floating` when checking input type for `opacity` instead of just `float` and `int`, so it becomes: `if not isinstance(opacity, (float, int, np.floating))`. This …

Fix error when using `VFadeIn` (and its subclasses)

---

manimlib/config.py
manimlib/mobject/vector_field.py

- Getting different input parameter in `self.init_style()` from `self.draw_lines()`, by removing the asterisk (*), the parameter `coords` would be passed as a numpy array in both functions.
- Setting a default value to 0 in `AnimatedStreamLines`. As `update()` function is called (with no arguments) in `mobject.py` (L845)

Resolving minor bug in StreamLines
